### ISSUE TITLE
Bump wharfie to latest

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-operator#11]
Bump wharfie to latest https://github.com/rancher/elemental-operator/blob/211ad46a9e2e7fc9cccf7f8e906df3c3da696352/go.mod#L121

see: https://github.com/rancher/elemental-operator/pull/3#issuecomment-1173929099

**Comment by kkaempf** [comment]
Dependencies with rancher-system-agent :-/

**Comment by pgonin** [comment]
rancher/wharfie releases:
[v0.4.3 ](https://github.com/rancher/wharfie/releases/tag/v0.4.3) => the one we currently use
[0.5.0](https://github.com/rancher/wharfie/releases/tag/v0.5.0) => Fix symlink/hardlink support and add path mapping support to CLI & Refactor registries package to support multiple endpoints
[v0.5.1](https://github.com/rancher/wharfie/releases/tag/v0.5.1) => Expose the tarball.GetOpener function
[v0.5.2](https://github.com/rancher/wharfie/releases/tag/v0.5.2) => Fix path handling and add e2e image extract test
[v0.5.3](https://github.com/rancher/wharfie/releases/tag/v0.5.3) => Fix support for trailing slash on endpoint URL

**Comment by pgonin** [comment]
update requested on system-agent ^^

**Comment by pgonin** [comment]
planned for 2.7.1

**Comment by pgonin** [comment]
@frelon https://github.com/rancher/system-agent/pull/102 it should be good to go to bump to wharfie 0.5.3
