### ISSUE TITLE
Checksum issue in MachineInventories

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#112]
Environment:
- Rancher 2.6.6
- Operator version 0.4.2, commit f243498, commit date git20220802

Issue saw in the `rancher/elemental` E2E test: https://github.com/rancher/elemental/runs/7648734615?check_suite_focus=true

After manual test the issue is that after Elemental OS installation the new node doesn't bootstrap the cluster part. With a quick check I can see that there is an issue with the checksum in `MachineInventories`, the `appliedChecksum` and the `checksum` variables are different, and there is now `failedChecksum` variable (which is expected in that case):
```
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  creationTimestamp: "2022-08-03T09:44:13Z"
  generation: 1
  labels:
    cluster-id: id-cluster-k3s
    manager: elemental-operator
    operation: Update
    subresource: status
    time: "2022-08-03T09:46:13Z"
  name: m-qemu-standard-pc-q35-ich9-2009-55392308-8b8f-4a04-b3b9-6
  namespace: fleet-default
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachineInventorySelector
    name: selector-cluster-k3s-nw4p6
    uid: 6432f38f-30f4-4905-9343-75519d0b7e56
  resourceVersion: "579181"
  uid: abc09ba2-65c1-4286-8346-2c61b7cd3e89
spec:
  tpmHash: 81ac219a55a63d5323da922872a5a27aee2f8cfb780dce328664ed0661f9a1e1
status:
  conditions:
  - lastUpdateTime: "2022-08-03T09:44:13Z"
    status: "True"
    type: Initialized
  - lastUpdateTime: "2022-08-03T09:46:13Z"
    status: "True"
    type: Ready
  - lastUpdateTime: "2022-08-03T09:46:13Z"
    status: "True"
    type: PlanReady
  plan:
    appliedChecksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    checksum: 17079797e37c49cf93f87d645b21f1484a4b706097763e9b02e81ca98fa055b8
    failedChecksum: 17079797e37c49cf93f87d645b21f1484a4b706097763e9b02e81ca98fa055b8
    secretRef:
      name: m-qemu-standard-pc-q35-ich9-2009-55392308-8b8f-4a04-b3b9-6
      namespace: fleet-default
```

I have no issue with on ISO image generated on 20220801 with this operator version:
- Operator version 0.4.1, commit 6b52b44, commit date git20220729

So the issue appears between the two version, but I wasn't able to find when exactly.

**Comment by Itxaka** [comment]
@ldevulder have you been able to reproduce this again?

**Comment by kkaempf** [comment]
No further reports. Please reopen if it happens again.

**Comment by ldevulder** [comment]
> @ldevulder have you been able to reproduce this again?

Sorry I forgot to answer... And I didn't had any issue anymore.
