### ISSUE TITLE
[operator] what is the --image-operator flag even for??

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-operator#113]
- Its mandatory
 - It also has a default value, so why is it mandatory?
 - the default is a non-existent image (rancher/elemental-operator)
 - The config of the image is never used
 - We already have the operator binary running, what is the image for?

Goes like this:
 - Asks for image to be provided
 - Has default image, dont care
 - Default image doesnt exists
 - Proceeds to ignore the image completely
 - Refuses to elaborate

Chad flag, doesnt care about its value but it needs to be specified LOL

IMHO, drop that flag it makes no sense anywhere!

**Comment by fgiudici** [comment]
is the legacy from early development and full parameter passing from the helm chart? 🤔 
we have a bunch of other parameters we pass there which seems not needed...

**Comment by Itxaka** [comment]
Others seems to make more sense as they are passed down the line to some of the controllers. But this one....

**Comment by Itxaka** [comment]
shiiiit, found it. Its actually passed to the syncer and used with the `display`command to gather the output of the custom syncer. Woah. https://github.com/rancher/elemental-operator/blob/main/pkg/services/syncer/types/custom.go#L100
