### ISSUE TITLE
elemental-operator images need ca data in them

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-operator#118]
When testing the channel version resources, using the json one, it tries to fetch data from the internet but it fails due to not being able to check the certificate. This is because the operator image only contains the binary on it thus any normal GET to an external resource will fail.

This should be a very simple fix:

`COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/`

**Comment by kkaempf** [comment]
Awaiting your pull (resp. submit) request 😝
