### ISSUE TITLE
Add "Rancher first step completed" to the docs

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-operator#123]
Currently the operator relies in rancher to have been configured to obtain the server-url, i.e. you need to complete the first step after installing rancher of going to the dashboard and setting a new admin password+url(which should be auto-filled) and accepting the rancher terms and conditions.

This is not mentioned anywhere in our docs so a clean install of rancher with no config done will result in the operator not being able to obtain the server-url.

We could always try to obtain the server-url in the same way that rancher does and only use it as fallback as to not have those kind of failures.

**Comment by fgiudici** [comment]
Fixed in https://github.com/rancher/elemental/pull/262
