### ISSUE TITLE
Improve debug logging in the operator

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#130]
When the operator is started in debug mode (--debug) it still misses some logging that should be expected indeed (e.g., when a MachineRegistration resource is created or when a registration url is accessed).
Moreover, some useless debug messages should probably go... 😅 
`time="2022-08-10T13:30:21Z" level=debug msg="Wrote ping"`

**Comment by Itxaka** [comment]
I think the wrote ping comes from the rancher libs as part of the keepalive, so you know the operator is working :)

al least I could not find that code in our side and believe me, I tried to remove it already :D
