### ISSUE TITLE
MachineInventory gets deleted when deleting a cluster

### ISSUE THREAD

**Issue by timirnich** [rancher/elemental-operator#139]
When a MachineInventory is assigned to a cluster (i.e. a corresponding MachineInventorySelector exists), deleting the cluster does not only delete the selector, but also the inventory. This removes the user's ability to control the machine after it has been removed from a cluster, unless it gets reprovisioned. It is also semantically counter-intuitive, since a MachineInventory can exist without the machine being assigned to a cluster before the machine joins a cluster. Therefore it should be possible to return to the same state by reducing the machine count in the cluster, or deleting the selector. 

As an aside, it is possible to create a new MachineInventory by power-cycling and re-provisioning the node via BareMetalHost in case of metal3 being used. But that is not necessarily always the case (metal3 being used that is). Elemental should be self-contained in this regard and not depend on other tools to recover machines.

**Comment by kkaempf** [comment]
That's coming from Rancher cluster provisioning, not from Elemental.

Deleting a MachineInventory at cluster deletion is correct, as the MachineInventory contains "cluster membership" information.
As we don't re-purpose installed machines, but redeploy instead, the MachineInventory will be re-created when redeployed.
