### ISSUE TITLE
[Epic] Elemental-operator scalability

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#147]
Check if / how the elemental-operator can scale.
Esp. if we can run multiple operators in parallel without problems.

 - [x] see how the operator scales and works in parallel https://github.com/rancher/elemental-operator/issues/149
 - [ ] see how many clients one operator can deal in burst with a set hardware baseline

**Comment by Itxaka** [comment]
I see this as two-fold

 - see how the operator scales and works in parallel (can you run 6 operator at the same time, do they clash with each other)
 - see how many clients one operator can deal in burst with a set hardware baseline (500? 1000? 10?)

This could also be tracked as well with benchmarks as part of the test suite to see if we introduce slowness over time.

**Comment by kkaempf** [comment]
> I see this as two-fold
> 
>     * see how the operator scales and works in parallel (can you run 6 operator at the same time or do they clash with each other?)
> 
>     * see how many clients one operator can deal in burst with a set hardware baseline (500? 1000? 10?)
> 
> 
> This could also be tracked as well with benchmarks as part of the test suite to see if we introduce slowness over time.

Full ack. I mark this issue as "epic" now and have splitted the first task as #149 <- that's the one that we should check asap, the rest can come later.

**Comment by juadk** [comment]
Maybe we can give a try to https://k6.io/open-source/ regarding bench-marking and burst the operator.

**Comment by Itxaka** [comment]
I was with you until I saw that the tests are written in js :P

I mean, it would be cool to keep all our our tests in golang and use the same approach we currently have. That would allow us to also check the internal go code benchmarks, if we add any. So not only benchmark the operator running but also the methods we are developing so we dont introduce extremely slow stuff.

**Comment by kkaempf** [comment]
I consider this done.
