### ISSUE TITLE
Friendlier URLs for registration endpoint

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#15]
If something goes wrong with a deployment, it would be nice to have a way to specify a nicer URL that people need to type in. This could also help with identifying which cloud-init was run when a machine registered. 

It might also be worth having a way to marking one of these as "default" to make the (maybe most common?) use case of only one registration endpoint being required.

**Comment by davidcassany** [comment]
I think this is a duplicate of #73, closing, feel free to reopen if I miss understood it.

**Comment by fgiudici** [comment]
This is related to #186
