### ISSUE TITLE
Investigate using Kubescape to scan our helm chart

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-operator#168]
Looks like kubescape can be used to scan helm charts and provide security information about best practices.

It also support scanning a full deployed cluster (including RBAC), which could also be useful to check if our resources are properly configured once deployed in the cluster.

It should be cool if we could run it as part of our CI to validate that we dont introduce any security issues on the chart

**Comment by kkaempf** [comment]
@ldevulder @juadk wdyt ? 🤔

**Comment by juadk** [comment]
We never touched the operator CI and I think it's not 100% QA but I guess it could be done with lower priority.

**Comment by kkaempf** [comment]
not planned
