### ISSUE TITLE
machineName option is not working as expected

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#190]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I did some tests with `machineName`: it works if, for example, I set `machineName: my-node` but it fails with `machineName: my-node-{{ trunc 4 .MachineID }}`, the `{{ trunc 4 .MachineID }}` was a syntax given by Ettore to be able to have a unique hostname for each node.

Maybe this syntax is not the same anymore? Or there is a bug here.

**What did you expect to happen:**

Custom hostname must be allowed and shouldn't be static.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

N/A

**Environment:**

- Elemental release version (use `cat /etc/os-release`): development version
- Rancher version: 2.6.8
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: All platform

**Comment by alexander-demichev** [comment]
Related issue: https://github.com/rancher/elemental-operator/issues/189

**Comment by fgiudici** [comment]
So, let's keep this to track the actual bug on the current `machineName` (has `trunc` support be dropped? If not let's add back `trunc` support; in any case we should document in detail what is allowed in the docs).
Let's instead keep the discussion on removing the `machineName` or how to ensure uniqueness on #189 .

**Comment by Itxaka** [comment]
FYI this came from the https://rancher.github.io/elemental-toolkit/docs/reference/cloud_init/#stagesstage_idstep_namehostname i.e. it was from before we cleaned up all the hostname stuff. That is only valid for cloud-config files, which get interpolated with templating. 
So in theroty you could still add that hostname by setting the proper config in the registration cloud-config, but that would probabyl get overriden by the default plan which sets the name to the machineName. And the k3s/rke hostname as well.

So I would  not play with that.

For our normal machineName in the registration, only the smbios data is used, nothing else. IMHO this should be closed.

**Comment by ldevulder** [comment]
> So in theroty you could still add that hostname by setting the proper config in the registration cloud-config, but that would probabyl get overriden by the default plan which sets the name to the machineName. And the k3s/rke hostname as well.

Yes it's overriden by `machineName`. But we could use `machineName` to force custom hostname. And after chacking in operator code I find a syntax that works, for example: `machineName: my-node-${System Information/UUID}`.

> only the smbios data is used

Yes it seems.

But as we have a way to generate custom and unique hostname I think that's fine for now. Let's see after some "real" users feedback if something else is needed.

Anyway, this bug can be closed yes.
