### ISSUE TITLE
Cant cross-compile register binary due to GCO_ENABLED

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-operator#192]
Looks like since we introduced CGO_ENABLED=1 for the register binary, we are not able to cross-compile for arm platforms on our release pipeline.

It usually fails via: `gcc: error: unrecognized command line option '-marm'; did you mean '-mabm'?`

We can try to build it by using the `gcc-arm-linux-gnueabihf` package which provides a gcc cross-compiler and using overrides on arm binaries

**Comment by Itxaka** [comment]
I disabled GCO_ENABLED=1 in arm builds for the moment as we need to have a proper release pipeline

**Comment by Itxaka** [comment]
Reopening as currently its only a workaround.

**Comment by Itxaka** [comment]
```
# itxaka @ zeus in ~/projects/elemental-operator on git:main x [16:08:29] C:2
$ CC=aarch64-suse-linux-gcc CGO_ENABLED=1 GOARCH=arm64 go build cmd/register/main.go
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.

```

**Comment by Itxaka** [comment]
I think its the same issue, we need to clone the full https://github.com/google/go-tpm-tools to have all the C libs available. Otherwise if you try to compile it and use the go dep manager, it only downloads go files so we cant fully compile it.


```
$ ls vendor/github.com/google/go-tpm-tools/simulator/*       
vendor/github.com/google/go-tpm-tools/simulator/README.md
vendor/github.com/google/go-tpm-tools/simulator/simulator.go

vendor/github.com/google/go-tpm-tools/simulator/internal:
doc.go  include.c  internal_cgo.go  internal_cross.go

```

**Comment by Itxaka** [comment]
was able to properly compile it without the go-tpm-tools under an arm64 docker container. It may be needed to compile it like that before running goreleaser if we want our arm github releases to have the full features.

Otherwise we just keep the arm64 without the tpm emulation.

**Comment by kkaempf** [comment]
LOL - that's **exactly** what I do when building the [elemental-operator rpm](https://build.opensuse.org/package/show/isv:Rancher:Elemental/elemental-operator)

**Comment by kkaempf** [comment]
We don't cross-compile.
