### ISSUE TITLE
Regression: the ServiceAccount created for MachineRegistration misses the link to the associated Secret.

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#197]
Operator version 0.6.0, commit d8810c9

**Comment by fgiudici** [comment]
The reported issue is logged in the operator logs:
`time="2022-10-05T15:47:32Z" level=info msg="Incoming HTTP request for /elemental/registration/kdlwmr2w929rgnkbqfrqbdrv5m6z4d74lwgb7lk4dx88dc8pmmbfgt"`
`time="2022-10-05T15:47:33Z" level=error msg="failed sending elemental cloud config: no secrets associated to the my-nodes service account"`

**Comment by fgiudici** [comment]
Cannot reproduce locally. Tested first with the elemental-operator chart built locally, then re-installing the operator from OBS:
`helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/charts/elemental/elemental-operator`

Creating a MachineRegistration creates a ServiceAccount with the linked Secret as expected.

**Comment by kkaempf** [comment]
Could it be the same problem I ran into when upgrading `elemental-operator` (and keeping the old `machineRegistration` in place) ?!

**Comment by fgiudici** [comment]
> Could it be the same problem I ran into when upgrading `elemental-operator` (and keeping the old `machineRegistration` in place) ?!

Well, it could have be. After checking with Andrew, this was not the case. I was able to reproduce:
It happens **only** if the MachineRegistration is created via the Rancher GUI with "Import".
If you kubectl apply -f the  same resource all works as expected.

**Comment by fgiudici** [comment]
The issue anyway is not present on github: it is only present in the OBS built chart.
After some testing, seems the issue is related to a change in the Chart annotation present in OBS only:
`catalog.cattle.io/namespace: cattle-elemental-operator-system`
This annotation is meant to fix the namespace and does not allow the user to use a different one (see https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps).
When we install the chart, we follow the Quickstart and force the `cattle-elemental-system` namespace. Changing the namespace during installation to match the one from the annotation seems to fix the issue.

**Comment by fgiudici** [comment]
So, basically installing the chart with:
`helm upgrade --create-namespace -n cattle-elemental-operator-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/charts/elemental/elemental-operator`
fixes the issue.

**Comment by kkaempf** [comment]
@mjura 👆🏻

**Comment by kkaempf** [comment]
Where, why, when, how was the `namespace` changed ???
https://rancher.github.io/elemental/quickstart/#preparing-the-cluster also has `cattle-elemental-system` instead of `cattle-elemental-operator-system`.

Esp. see #9 !!
