### ISSUE TITLE
Missing spec:config in MachineRegistration causes panic in the Operator

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#202]
If the Spec of the MachineRegistration is not conformant to the [reference](https://rancher.github.io/elemental/machineregistration-reference/), the MachineRegistration is created anyway but with an empty `spec`.
When a client performs an unauthenticated request to retrieve the registration yaml, the operator panics on the null spec:
----
`time="2022-10-10T13:50:19Z" level=info msg="Incoming HTTP request for /elemental/registration/jwp44t2xd2kpzjsq4g9rmwc297xdnrwmkdlc6cz6qrbcclgmdt8m7f"`

`2022/10/10 13:50:19 http: panic serving pipe: runtime error: invalid memory address or nil pointer dereference
goroutine 8996 [running]:`

`net/http.(*conn).serve.func1()
	/usr/lib64/go/1.19/src/net/http/server.go:1850 +0xbf`

`panic({0x19b9060, 0x2dde1a0})
	/usr/lib64/go/1.19/src/runtime/panic.go:890 +0x262`

`github.com/rancher/elemental-operator/pkg/server.(*InventoryServer).unauthenticatedResponse(0xc0005b6000?, 0xc000545680, {0x1f02300?, 0xc000696540})`

	/home/abuild/rpmbuild/BUILD/elemental-operator-0.6.0+git20221003.d8810c9/pkg/server/register.go:125 +0x52

`github.com/rancher/elemental-operator/pkg/server.(*InventoryServer).ServeHTTP(0x1f1a518?, {0x1f194f8?, 0xc000696540}, 0xc0005b6000)`

	/home/abuild/rpmbuild/BUILD/elemental-operator-0.6.0+git20221003.d8810c9/pkg/server/register.go:60 +0x645

**Comment by Itxaka** [comment]
nice one, indeed we try to get the spec of a machineregistration without checking if its valid, althougth I would expect the apply to fail if the spec is malformed!

@fgiudici did you get the broken machineregistration yaml? Maybe we could incorporate it in our tests :D

**Comment by fgiudici** [comment]
> nice one, indeed we try to get the spec of a machineregistration without checking if its valid, althougth I would expect the apply to fail if the spec is malformed!
> 
> @fgiudici did you get the broken machineregistration yaml? Maybe we could incorporate it in our tests :D

I didn't get the actual yaml config, I were just able to get a picture of it, so didn't transcribed the text... as it basically just had a `cloudConfig:` section directly under the `spec:` : I expect that just putting any custom unexpected section under the `spec:` would reproduce this issue
