### ISSUE TITLE
Track the installation status of a new host in the associated MachineInventory resource

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#214]
Since new elemental hosts can be provisioned automa..gically 🪄  just inserting a live ISO, unattended installations are a likely scenario.
It could be of help then to track at the operator level the Status of the installation on new hosts. MachineInventory looks clearly the candidate resource to track this.
The specific scenario to address is the one enabled in #202 : the host can boot and fail the installation because the target device is missing from the MachineRegistration configuration.
The error message describing the issue will only be available in the remote host system log. On the operator side all will look fine, with the MachineInventory waiting on the Status to be applied.

We need some feedback from the register client if installation fails.

**Comment by anmazzotti** [comment]
Consider including the reset status within this issue, since the logic should be similar.
Note that `elemental-register` has now `--install` and `--reset` arguments so these actions are explicit.

**Comment by kkaempf** [comment]
See also #433

**Comment by kkaempf** [comment]
Fixed in CAPI
