### ISSUE TITLE
OS update API

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#227]
Note: this might be a documentation issue

There's confusion how to visualize `ManagedOSVersion`, `ManagedOSVersionChannel`, and `OSImageUpgrades` in the UI.

We should either provide clear documentation or put a better API on top of these concepts to make it easier to consume it from the UI,

**Comment by alexander-demicev** [comment]
We might want to wait for kubebuilder migration with this, as I discovered some issues with the API design.

**Comment by fgiudici** [comment]
ManagedOSVersion and ManagedOSVersionChannel data are now correctly visualized in the UI.
Completed, closing the issue.
