### ISSUE TITLE
Generic documentation on API design for UI consumption

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#228]
For the work on #207, #226, and #227 we need to better understand what kind of API (kubernetes api, rancher api, ...) the UI needs.

**Comment by aalves08** [comment]
@kkaempf I would say any REST api would suffice given that it's uses the login credentials/auth token (not sure which we use currently) for rancher API so that we don't need to provide a new token for a new API. 

Maybe @nwmac can help giving a bit more insight/details. Thanks

**Comment by kkaempf** [comment]
From today's call:
* REST preferred
* async operation, might take longer to perform
* kick-off with POST request, return handle
* use handle to get status, result or error message
* result might be large (like ISO download)
* @aalves08 to provide examples based on Rancher API

**Comment by alexander-demicev** [comment]
also, the question is should we use aggregated API server or new CRDs?

**Comment by kkaempf** [comment]
@aalves08 @nwmac 👆🏻

**Comment by fgiudici** [comment]
Talked a bit with @aalves08 , summing up here the main points:
- REST APIs easier to integrate on the UI side (no websocket).
- 2 APIs could be enough:
  - one for triggering the ISO build
  - one for checking the status of the build process (UI will poll) and get the 
 
One good point raised by @aalves08 is that we should take into account Elemental OS images: in the UI, the user picks up a MachineRegistration and *a specific Elemental OS image* that will be used as the base for the ISO creation.
Good point from @alexander-demicev above: I would say that we could use the web server already in the Operator that deals with the registration but for managing the OS versioning (and returning the url for ISO download) we may require new CDRs... for sure we should extend current MachineRegistration.
Something to be defined as part of this card.

**Comment by kkaempf** [comment]
With REST, it should be a single API endpoint with different verbs (POST to start, HEAD for status, GET for download ...) ?!

**Comment by aalves08** [comment]
Correct @kkaempf . I think @fgiudici just made a typo there: 

> 2 APIs could be enough:

I believe what he meant was 1 API, 2 endoints:
/iso-build -> POST - trigger iso build
/iso-build -> GET - get iso build status
/download -> GET - download ISO

Something along those lines, I think. Correct me if I am wrong @fgiudici 🙏

**Comment by aalves08** [comment]
> also, the question is should we use aggregated API server or new CRDs?

Imho, I think there is a question to be answered here:
Are we going to "manage" iso builds in the future? 

Not really sure on what the future of the product will be.  I think that may influence if the implementation goes for an API or a CRD.

Maybe @agracey can pitch in on this topic 🙏 

Given the current scope, API seems like a solid option for now.

**Comment by kkaempf** [comment]
ISO specifics should be followed up in #207 😉

**Comment by kkaempf** [comment]
Done. Follow-up are API specific like #207
