### ISSUE TITLE
Kubebuilder: Refactor e2e tests to controller runtime

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/elemental-operator#240]
Our E2E tests for operator are not using controller-runtime. We should refactor them to use new API definition and client.
Example of a suite where new client is used https://github.com/rancher/elemental-operator/blob/main/tests/e2e/machineregistration_test.go#L52

**Comment by mjura** [comment]
List of tests to refactor

- [ ] MachineRegistration - done in https://github.com/rancher/elemental-operator/pull/253
- [ ] ManageOsVersionChannel 
- [ ] ManageOSImage
- [ ] Upgrades

**Comment by mjura** [comment]
Tests were refactored
