### ISSUE TITLE
Add more system data to register workflow

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-operator#272]
We can add disks, memory and more to the data we send from the node into the operator for the registration.

Consider using the ghw library for this.

In the future that data could be used in conjuntion with the selector controller to select the nodes in much more detail

**Comment by fgiudici** [comment]
yep, great idea! There seems to be some interest in getting more data from the registering hosts so to be able to make more fine grained selections in the MachineSelector :-)

**Comment by Itxaka** [comment]
For that we should either have some default labels or maybe a configmap with all the data that we got somehow as the selector would try to access that data much later in the process and we cannot assume that the data has been transferred from teh registration process into the inventory.


But that is for another card I guess :)

**Comment by Itxaka** [comment]
This is already implemented on https://github.com/rancher/elemental-operator/pull/276
