### ISSUE TITLE
OBS built operator has no commit hash or commit date

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#275]
It shows
```
"Operator version 1.0.0, commit , commit date 1"
```

**Comment by davidcassany** [comment]
By the way it drives me mad having spec files and dockerfiles only in OBS and not in github sources. Makes having the both in sync a PITA, is is too easy to forget updating the spec/dockerfile and we discover the mismatch few weeks after when no one rememebers. Also I'd love to see PRs building the RPMs in OBS, currently doable with OBS workflows. Gonna create a discussion/card around these topics, next release needs to be easier and better.
