### ISSUE TITLE
v1beta2 API planning

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/elemental-operator#283]
We've recently released the first API version, this means we'll be collecting feedback from users soon.  By creating a v1beta2 API we can address comments like renaming/adding API fields, possibly moving them.
After we merge kubebuilder related code into main it will be possible for us to start working on a new version of API. Kubebuilder supports an easy way of automatical conversion from v1beta1 to v1beta2 - https://book.kubebuilder.io/multiversion-tutorial/conversion.html

This issue is created to store feedback and planning future work.

**Comment by kkaempf** [comment]
not planned
