### ISSUE TITLE
Elemental upgrade with ManagedOSVersionChannel fails

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#288]
The [CI test](https://github.com/rancher/elemental/actions/runs/3638142972) shown an issue on OS upgrade with `ManagedOSVersionChannel` with the `main` version of elemental-operator.
No issue with the same test on elemental-operator v1.0.0 (see [here](https://github.com/rancher/elemental/actions/runs/3638147780)).

After applying file I have nothing created in `ManagedOSVersion` and the status of `ManagedOSVersionChannel` looks weird:
```
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"elemental.cattle.io/v1beta1","kind":"ManagedOSVersionChannel","metadata":{"annotations":{},"name":"os-versions","namespace":"default"},"spec":{"options":{"Timeout":"1m","URI":"http://192.168.4.44:8000/tests/assets/osVersions.json"},"type":"json"}}
  creationTimestamp: "2022-12-07T10:22:53Z"
  generation: 1
  managedFields:
  - apiVersion: elemental.cattle.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
    manager: elemental-operator
    operation: Update
    subresource: status
    time: "2022-12-07T10:22:53Z"
  - apiVersion: elemental.cattle.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:options:
          .: {}
          f:Timeout: {}
          f:URI: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-12-07T10:22:53Z"
  name: os-versions
  namespace: default
  resourceVersion: "137960"
  uid: 804a0e33-86c7-450f-8038-99f200455fa2
spec:
  options:
    Timeout: 1m
    URI: http://192.168.4.44:8000/tests/assets/osVersions.json
  type: json
status:
  conditions:
  - lastTransitionTime: "2022-12-07T10:22:53Z"
    message: spec.SyncInterval is not parseable by time.ParseDuration
    reason: InvalidConfiguration
    status: "True"
    type: Ready
```

You'll find attached the operator logs as well as the configuration files used (all in the same ZIP file).
[managedOSVersionChannel-issue.zip](https://github.com/rancher/elemental-operator/files/10176801/managedOSVersionChannel-issue.zip)

**Comment by alexander-demicev** [comment]
We added a new API field for this object https://github.com/rancher/elemental-operator/blob/controller_runtime/api/v1beta1/managedosversionchannel_types.go#L40, controller fails to parse its value because the field is missing. Currently, it's marked as optional, there are 2 solutions to the problem: remove the optional tag and require users to fill it or add a reasonable default 
cc @davidcassany

**Comment by alexander-demicev** [comment]
I think this should not be a blocker for merging new controllers, we can fix it afterward before releasing the first version of new controllers.

**Comment by ldevulder** [comment]
> I think this should not be a blocker for merging new controllers, we can fix it afterward before releasing the first version of new controllers.

I think so, I just tested manually and it works after the addition of `syncInterval`. So for the E2E test I will simply add a `syncInterval: 5m` entry.

**Comment by davidcassany** [comment]
> We added a new API field for this object https://github.com/rancher/elemental-operator/blob/controller_runtime/api/v1beta1/managedosversionchannel_types.go#L40, controller fails to parse its value because the field is missing. Currently, it's marked as optional, there are 2 solutions to the problem: remove the optional tag and require users to fill it or add a reasonable default
> cc @davidcassany

Indeed I was aware there would be this problem. I believe we can simply add a reasonable default in case the string is empty (in which case we can assume it was never provided).
