### ISSUE TITLE
elemental-operator and elemental-cli differ in what they accept as install options

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#296]
`elemental-cli`'s set of [install variables](https://github.com/rancher/elemental-cli/blob/5ae32204b0f2160365c8d64997068b2be1a25133/pkg/types/v1/config.go#L134) is different from [`elemental-operator`'s set](https://github.com/rancher/elemental-operator/blob/af83eea27fbc5b2149c48bf4fef367aa72b77035/api/v1beta1/types.go#L21) 🤔 

See also [this comment](https://github.com/rancher/elemental-cli/issues/393#issuecomment-1351967246)

imho, `elemental-cli` and `elemental-operator` should be consistent in what they accept.

**Comment by davidcassany** [comment]
Note any installation config supported by `elemental install` can also be  passed to the registration as documented in https://elemental.docs.rancher.com/customizing#customize-installation-iso-and-installation-process , this is a bit convoluted procedure for such simple flag, but just to point we can actually make use of all `elementa install` potential when registering.

I am creating related PRs to include this flag in the operator install API.
