### ISSUE TITLE
Evaluate usage of gorilla/websocket

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-operator#305]
The gorilla toolkit project is being archived: https://github.com/gorilla/

We should probably migrate to another websocket package that will be maintained, for example: [gobwas/ws](https://github.com/gobwas/ws) or [nhooyr/websocket](https://github.com/nhooyr/websocket)

**Comment by fgiudici** [comment]
Oh right, will be archived by the end of the year...  good point, it is not super-urgent but we have to plan for the move.

**Comment by pgonin** [comment]
It appears to be used in rancher more generally.
https://github.com/rancher/rancher/blob/1f014b7fcd734e9321555b613cc28b1b12bf8eeb/pkg/ui/routes.go#L6
https://github.com/rancher/remotedialer/blob/0018e88e72de6eb8714acab029ea01376d4678e2/wsconn.go#L10
https://github.com/rancher/pipeline/blob/11e4b3f18f9a3502637fcf161bc1463cf74d5a99/server/conn_holder.go#L11
https://github.com/rancher/norman/blob/96b95e3475e0dd39b49bf27082c3f9f440b336e9/pkg/subscribe/handler.go#L9
https://github.com/rancher/norman/blob/96b95e3475e0dd39b49bf27082c3f9f440b336e9/pkg/subscribe/handler.go#L9

I would make that a more general issue for Rancher engineering teams to work out a plan to a new websocket package

cc @mattfarina

**Comment by pgonin** [comment]
suggestion from @MbolotSuse 
"Would probably be good for us to start with the std lib package: https://pkg.go.dev/golang.org/x/net/websocket unless we have specific objections to that (there probably are given the number of alternative packages, but I'm not sure what they are)."
also see https://github.com/rancher/rancher/issues/39862

**Comment by anmazzotti** [comment]
Just to add to this discussion, it would be worth to consider replacing websocket usage with [gRPC](https://grpc.io/).  
We would have the benefit of being able to describe our protocols through a standard [protobuf](https://protobuf.dev/overview/) definition. 

This would make it more consumable for third parties and easier to understand.
On the development side, it would make the code simpler, as we would not need websocket boilerplate code anymore. We could also rely on gRPC for authentication.

**Comment by fgiudici** [comment]
Seems the project has been resurrected by an handful of new core developers: https://gorilla.github.io/blog/2023-07-17-project-status-update/ 🥳
