### ISSUE TITLE
[BUG] Elemental UI Operator install fails on hardened local clusters. 

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/elemental-operator#317]
**Rancher Server Setup**
- Rancher version: v2.7.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- v1.24.4
- local HA hardened 

**Describe the bug**
after the user has installed extensions and the elemental UI extension, following these [steps ](https://elemental.docs.rancher.com/elementaloperatorchart-reference/)to install the Elemental Operator results in a failure to install. 

the deployment shows status of `Deployment does not have minimum availability.`
the pod shows status of `Containers with unready status: [elemental-operator]`

**To Reproduce**
1. stand up hardened HA cluster
2. click extensions
3. install the extensions operator and repository
4. install the elemental UI extensions on the extensions page (may have to refresh page for it to be visible)
5. follow [these ](https://elemental.docs.rancher.com/elementaloperatorchart-reference/)directions to install the elemental operator 

**Result**
the operator never installs. 

the deployment shows status of `Deployment does not have minimum availability.`
the pod shows status of `Containers with unready status: [elemental-operator]`

**Expected Result**
operator installs as expected

**Screenshots**
<img width="750" alt="image" src="https://user-images.githubusercontent.com/89030218/208960292-468609c3-8508-4e0b-b609-f87893f173db.png">

**Additional context**
- @Itxaka investigated and found this was due to PSP rules.

- the operator installs correctly on unhardened clusters

**Comment by Itxaka** [comment]
FYI PSP is deprecated for a long time and dropped on k8s 1.24 I think. I wonder what substitutes it and if we are ready for that.

Also IIRC the issue was that our container does not specify an USER directive, so k8s is unable to identify if the container runs as root or not and will refuse to run it as the hardened policy límited running containers with root.

So maybe adding an USER directive to our container may fully fix this and allow it to run as not root

**Comment by agracey** [comment]
> So maybe adding an USER directive to our container may fully fix this and allow it to run as not root

I'm pretty sure this is true but we might also need to change the securityContext->runAsUser in the PodSpec. If so, should we patch the 1.0 release container or just add a note to the docs that it's fixed in the upcoming release?

**Comment by frelon** [comment]
@agracey Closing this as completed, will try to get a note included in the release-notes for next release!

**Comment by juadk** [comment]
While I was reading documentation and building my k3s hardened cluster,  indeed, PSP will be removed in k8s 1.25+ and replaced by Pod Security Admissions (PSAs).
