### ISSUE TITLE
Node labels flag set incorrectly

### ISSUE THREAD

**Issue by dgiebert** [rancher/elemental-operator#318]
### Description
Currently, the file `/etc/rancher/k3s/config.yaml.d/99-elemental-inventory-labels.yaml` sets the node-label flag incorrectly.

### Error
`Incorrect Usage: flag provided but not defined: -NodeLabels`

### Fix
Changing `NodeLabels:` to `node-label:`

Edit: I have used two pools (control-plane + agents)

**Comment by dgiebert** [comment]
Seems to relate to the issue https://github.com/rancher/elemental-operator/issues/285 and the MR: https://github.com/rancher/elemental-operator/pull/286

Might be this line: https://github.com/rancher/elemental-operator/blob/4e31fe2fe7daee7f40c1e4b4ab5cceb7fa38c57c/controllers/machineselector_controller.go#L339

**Comment by frelon** [comment]
Seems like a regression of https://github.com/rancher/elemental-operator/pull/287 I will bring back the fix and test today
