### ISSUE TITLE
operator: add support in newer operator to older register clients

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#325]
In elemental-operator 1.1.0, we introduced quite a rework adopting kubebuilder.
This required to deal with variable data, i.e., the cloud.-config part, in a different way which is incompatible with the older 1.0.x register client.
The operator right now detects the older client, but it just prints a warning about a possibly not applied cloud-config configuration in the operator logs, but allows the installation to go on.
The end result is that the host will be provisioned, but not with the cloud-config data specified by the user.
~This could go easily unnoticed for quite some time: better to stop the installation on the operator side in this case.~
Let's introduce backward compatibility: the operator upon detection of an older client should send the configuration in the legacy format.

**Comment by rdoxenham** [comment]
Confirmed on v1.10.0 with a stable ISO (i.e. older client):

```
% kubectl logs -n cattle-elemental-system elemental-operator-8748fb9fb-nsgk8 | grep -i warn        
time="2023-01-11T09:39:50Z" level=warning msg="Detected old elemental-register client: cloud-config data may not be applied correctly"
```

**Comment by Itxaka** [comment]
isnt it possible to tranform the older cloud-config data into the newer? At least maybe for a while until its fully deprecated?

**Comment by fgiudici** [comment]
yes, wouldn't be too complex but would mean to deal with the old structure, do conversion just for the registration if and only if an old register client is detected: registration code would become a bit more convoluted. Would that be worth? That's the point. But let's leave it as something to evaluate in this card.

**Comment by dsmithbauer** [comment]
I saw this exact behavior today as well using the latest Stable elemental-teal ISO and elemental-operator 1.1.0
`time="2023-01-11T17:26:09Z" level=warning msg="Detected old elemental-register client: cloud-config data may not be applied correctly"`

**Comment by fgiudici** [comment]
The stable elemental ISO on OBS is an older version, 1.0.x.: this should be fixed.
As a temporary workaround you can use the Staging ISO version, with should be aligned with the latest releases:
`REPO=Staging ./elemental-iso-add-registration reg.yaml`

**Comment by kkaempf** [comment]
Well, a Stable (old) ISO against a Dev (new) operator should 'just work'. No ?!

**Comment by fgiudici** [comment]
> Well, a Stable (old) ISO against a Dev (new) operator should 'just work'. No ?!

In this case we have to explicitly support old ISO (old register clients) in newer operator (kubebuilder based): data structure carrying cloud config data had to change and  the marshal / unmarshal wouldn't work.

**Comment by fgiudici** [comment]
PR adds support to older register clients (old ISO).
