### ISSUE TITLE
registration: register client lacks support to elemental operator with lower registration protocol version

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#331]
In  https://github.com/rancher/elemental-operator/pull/266 we introduced register protocol version negotiation during the registration phase between the register client and the elemental operator.
We had put effort to enable the operator side to play nicely with register clients supporting lower versions. Anyway, we didn't took care of the support on the client side of lower version on the operator side.
We should either add the support in the register client or let the operator refuse to serve clients declaring newer versions not already supported.

**Comment by fgiudici** [comment]
I would be in favor of the former (i.e., add support on the client side of older operator versions).

**Comment by kkaempf** [comment]
Given the amount of people already using (experimenting with) Elemental, I'd welcome if operator >= 1.1 would support clients < 1.1

I hope that's doable with a reasonable (days, not weeks) effort 🤞🏻
