### ISSUE TITLE
Only release charts using gh-pages are helm repos

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#333]
The only publicly available binaries released in Elemental should be the ones from OBS/IBS, with the sole and only exception of the helm charts.

The idea is to release charts in github pages with the following pattern:

* Moving Dev charts on head triggered on each main merge pointing to Dev artifacts
* Moving Staging charts on each tag pointing to Staging artifacts
* Manual Stable charts releases based on a tag pointing to Stable artifacts (keeps all versions)

**Comment by fgiudici** [comment]
related: https://github.com/rancher/elemental-operator/issues/438

**Comment by davidcassany** [comment]
I wanted to also publish in ghcr the charts to provide backward compatibility to previous OCI deployment scenarios but publishing in ghcr seams to be quite complex, specially if we want to delete previous builds (we want a single `Dev` build):

* Containers are mapped to GH packages
* It's problematic deleting them it is an organization wise operation
* Problematic to define paths in gh

So IMHO we have three options:

1. Add a small breaking change in elemental-operator installation procedure (use repos instead of OCI artifacts)
2. Do not publish charts in gh-pages and keep using OBS
3. Try to push OCI generated artifacts from OBS to some https repository (gh-pages?). We could use `helm pull <OBS-uri>` and generate an http repos on gh-pages. The challenge is waiting until charts are published (should be possible with [rabbit](http://rabbit.opensuse.org/), but I have no experience at all using it)

**Comment by davidcassany** [comment]
Finally I implemented the third option only for staging and stable environments, for the time being this is enough as discussed across the team this is enough to start moving.
