### ISSUE TITLE
Move to config.Config instead of config.Install in MachineRegistration

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-operator#34]
We want to be able to pass by the whole [config.Config](https://github.com/rancher/elemental-operator/blob/14d4d957cf5dac336375686754698e6fd6df7fd9/pkg/config/config.go#L74) instead of install.Install in the MachineRegistration spec [here](https://github.com/rancher/elemental-operator/blob/14d4d957cf5dac336375686754698e6fd6df7fd9/pkg/apis/elemental.cattle.io/v1beta1/registration.go#L41) and  [here](https://github.com/rancher/elemental-operator/blob/14d4d957cf5dac336375686754698e6fd6df7fd9/pkg/server/register.go#L191) when we return the data via wss server.

This mean also that we must merge the two config structures (the one pass by the user, with free-form fields) and the one that we generate when we return the data from the wss server.

**Comment by Itxaka** [comment]
duplicated of #33
