### ISSUE TITLE
build-image API: build job PODs lifecycle management

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#355]
* Do proper cleanup of build PODs
* Only one image build job (POD) at a time allowed (for now) 
* The latest image built will be kept in the Cluster till another build job is started

**Comment by kkaempf** [comment]
For the initial release, I'd limit the number of parallel builds to 1.

The POD should be terminated as soon as the image download is complete.

**Comment by fgiudici** [comment]
- for now, 1 build at a time allowed, but we ensure the code to be ready for concurrency when we will extend
- the build is kept around till another one is requested: this way, the last built image will be always available for download
- the URL will be reachable only within the Rancher cluster, how to expose that to be addressed in https://github.com/rancher/elemental-operator/issues/356
