### ISSUE TITLE
build-image API: build job: ensure container images are published on OBS

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#357]
We need to publish the image to expose the ISO on a container registry

**Comment by kkaempf** [comment]
Can't we download the image directly from the build (without the need to move it to another storage) ?

**Comment by fgiudici** [comment]
The issue description is a bit ambiguous:  this issue is about the container images used inside the Pod that do the actual build of the image (and that allows the final image to be downloaded).
For the build image, we will use the elemental build image in OBS.
The current image for allowing the download of the built ISO is a temporary one, we should pick a more official one.

**Comment by fgiudici** [comment]
Switched the container image to expose the built ISO to opensuse nginx image in PR #369 .
After some discussion we may want to add a simple http server to the build container image we already publish in OBS.
In any case, the container image used right now is published on OBS.
