### ISSUE TITLE
Cannot use a cluster name longer than 14 characters

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#365]
In our UI e2e test, cluster's name is `myelementalcluster`, it looks too long when bundle is created:

```
kubectl get bundles -A
NAMESPACE       NAME                                                       BUNDLEDEPLOYMENTS-READY   STATUS
fleet-default   mcc-myelementalcluster-managed-system-upgrade-controller   0/1                       ErrApplied(1) [Cluster fleet-default/myelementalcluster: release name "mcc-myelementalcluster-managed-system-upgrade-controller": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53]
 ``` 

That means name longer than 14 characters cannot be used.

Do not know what is the best way to handle it bu I also tried with `os-upgrader` and it truncates the random name as long as the update name is long.

For instance:
- With "nomal" name:
`apply-os-upgrader-myupdate-on-m-8bf6eafc-a35c-4cbb-93b9-3-xjt7k`

- With long name:
`apply-os-upgrader-veryveryveryveryverylongupdatename-on-m-jrbdj`

**Comment by kkaempf** [comment]
@aalves08 does Rancher dashboard have a check on length of cluster name ?

**Comment by aalves08** [comment]
@kkaempf currently we don't have that check on the frontend.

**Comment by juadk** [comment]
There is exactly the same issue recorded in rancher repo: https://github.com/rancher/rancher/issues/40565

**Comment by manno** [comment]
This happens when bundles are created directly, like in 
* https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/provisioningv2/managedchart/managedchart.go#L94-L118
* https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go#L124-L148

Fleet added more safeguards in https://github.com/rancher/fleet/pull/1353 and backports.
Rancher fixed that in https://github.com/rancher/rancher/pull/40725/files

**Comment by juadk** [comment]
Thanks @manno 

I just deployed `rancher-head` + `elemental-ui 1.1.0` and all looks good now:
```
root@jadamek-elemental-s-2vcpu-4gb-fra1-01:~# kubectl get bundles -A
NAMESPACE       NAME                                                    BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local     fleet-agent-local                                       1/1                       
fleet-default   fleet-agent-myveryveryveryverylongclustername           1/1                       
fleet-default   mcc-myveryveryveryverylongclustername-managed-3da117    1/1                       
fleet-default   myveryveryveryverylongclustername-managed-syste-cdffc   1/1                       
fleet-default   mos-upgrade                                             1/1   
```

I was able to upgrade my elemental node as expected.
