### ISSUE TITLE
Define version compatibility and update order between operator and register

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#375]
Making all operator versions backward and forward compatible with all register versions is a huge effort (and not worth it imho).

We need to define
- which operator versions are compatible with which register versions
- upgrade scenarios (operator first vs. register first)

**Comment by kkaempf** [comment]
See also #329

**Comment by fgiudici** [comment]
Adding a couple of notes on this:

Making choices on the interoperable versions should consider also the way we  build the registration image.
Right now it is built via a script which takes the registration client from the stable OBS repo.
If a user installed the "old" stable operator, as soon as we update the Stable channel, if the user prepares a new ISO for his "old" operator the ISO may likely carry a client with a registration protocol newer than the one on the operator side, without the user even noticing.

Keeping version compatibility with pre-kubebuilder releases is not trivial (see #373). Anyway, from the introduction of the registration protocol version negotiation on (https://github.com/rancher/elemental-operator/pull/266), managing different versions is already embedded in the registration protocol code.
If any major change will happen (data structures or kubernetes APIs) we can either manage the change or gracefully stop the registration process with a clear explanation (and add it also in the operator logs).

**Comment by davidcassany** [comment]
This has been already discussed and agreed there is no compatibility with ISO v1.1.4 and elemental-operator v1.0.2. All other combination are supported.
