### ISSUE TITLE
Review MachineInventory adoption logic

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#382]
The adoption logic of the MachineInventorySelector to adopt ManchineInventory resources might not be robust and performant enough. This logic seams to be one of the causes of the rancher/elemental#667, the current logic seams to cause a burst of reconcile loops on MachineInventorySelector controller that caused inconsistent adoptions that the controller was not capable to detect and sanitize.

On rancher/elemental#667 we some the controller stabilize with the following result:

```
Inventories:

* name: node-7ed03937-b095-4a80-ae48-f843eccda8da
  owner: selector-master-cluster-k3s-4m8vg
  
* name: node-6ce0d98c-4b8f-45db-9eeb-b08c917a0ba7
  owner: selector-master-cluster-k3s-4m8vg
  
* name: node-8a3825e9-2cb4-46cd-b36f-b702be321f92
  owner: selector-master-cluster-k3s-8d75g
  
Selectors:

* name: selector-master-cluster-k3s-lt6xw
  owns: _none_
  
* name: selector-master-cluster-k3s-4m8vg
  owns: node-6ce0d98c-4b8f-45db-9eeb-b08c917a0ba7
  
* name: selector-master-cluster-k3s-8d75g
  owns: node-8a3825e9-2cb4-46cd-b36f-b702be321f92
```

Note there are two MachineInventories that are owned by the same MachineInventorySelector, this should not happen. Apparently this was caused by the same MachineInventorySelector reconciling repeatedly too fast and adopting a different inventory on each loop because between two the loops the cached resources where not yet updated. This raise two concerns:

* Why are we having insane bursts of reconcile loops in that controller and how to prevent it form happening. I believe one of the problems is that the controller is also watching MachineInventory changes and within the reconcile loop such a resources is changed to set the new ownership, so before we even end the current loop another one within the same resource is requested.
* Is there a way to make this logic more robust, so in the hypothetical case we end up in an inconsistent state like the one above the reconcile loops of related resources are capable to detect it and act. I believe that probably some sort of acknowledgement logic could make sense here, so to finalize the adoption successfully the inventory reconcile loop needs to verify the owner has the expected status, so both are aware of is relationship.

Ideally the solution for rancher/elemental#667 should not be disabling caching. Also if we have bursts without caching this could eventually turn into a performance problem. I consider #381 a good workaround but not a complete solution.

**Comment by agracey** [comment]
Since this is a race condition, I'm also wondering how scaling the operator would affect it?
