### ISSUE TITLE
Upgrade from stable to staging breaks due to helm annotations

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#383]
Finally going to upgrade my demo setup from 1.0 to staging and ran into the lack of helm annotations.

```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "machineinventories.elemental.cattle.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "elemental-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-elemental-system"
```

Is there a way to get helm to pull the old CRDs in without needing to uninstall/reinstall?

**Comment by davidcassany** [comment]
mmm weird, which is the stable version you were on the elemental-operator? feels like you are hitting an old issue https://github.com/rancher/elemental-operator/issues/241#issuecomment-1333979122 
Upgrade to staging works starting from v1.0.2

**Comment by agracey** [comment]
You are correct and my google-fu was failing me this morning :(
