### ISSUE TITLE
Test backup/restore (to verify elemental-operator#9)

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#387]
Do we still need #9 ?

Please do a quick backup/restore test to verify if all Elemental resources are restored.

**Comment by ldevulder** [comment]
Yes it's still needed. @pgonin PR https://github.com/rancher/rancher/pull/39064 should be rebased and merge to have the backup/restore functionality.

**Comment by ldevulder** [comment]
New updated version: https://github.com/rancher/rancher/pull/40933, waiting for validation and merge.

**Comment by kkaempf** [comment]
rancher/rancher#40933 got merged today 🤯
