### ISSUE TITLE
Elemental remote plan information

### ISSUE THREAD

**Issue by sudheermygapula** [rancher/elemental-operator#395]
**What steps did you take and what happened:**
I am analyzing the remote plan concept , Could it be possible to create custom remote plans after the bootstap phase is completed ? What is guidance for custom remote plan ?

**What did you expect to happen:**
Able to create custom remote plan after the elemental installation done  ( for example updating file content ).

**Anything else you would like to add:**
It would be nice how the boot strap plan is created ( high level documentation ) and guidance how to use the remote plan concept.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="SUSE Linux Enterprise Micro for Rancher 5.3"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
IMAGE_REPO="registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal/5.3"
IMAGE_TAG="1.0.0-33.59"
IMAGE="registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal/5.3:1.0.0-33.59"
TIMESTAMP=20230308213533
GRUB_ENTRY_NAME="Elemental"

- Rancher version: 2.7.1
- Kubernetes version (use `kubectl version`): v1.24.8+k3s1

- Cloud provider or hardware configuration: IPC

**Comment by sudheermygapula** [comment]
@agracey  for now i forsee updating / configuring the nework interfaces accroding to customer/plant network . For example if the edge hardware having 3 network interfaces one reserved for cloud connectivity and one for plant ( PLC) network and one reserved for service user. Some times this network configurations need to be adjusted to envivorment which varies from customer to customer.  Overall the concept could be helpfull to update such kind of configurations after installation of elemental .

**Comment by agracey** [comment]
Would this hardware configuration (typically) look the same across all hardware? Do you need ad-hoc, per-node configuration prior to Kubernetes being provisioned?

**Comment by sudheermygapula** [comment]
- ad-hoc configuration per-node ( in some cases multiple hardware belong to same customer might be applied with same configuration ) could be good which can be extended to group of hardware.

- Not necessary prior to kubernates provisioned could be case after provisioned also ( for example some time corporate network proxy configuration changes which need to be applied )

**Comment by davidcassany** [comment]
> * ad-hoc configuration per-node ( in some cases multiple hardware belong to same customer might be applied with same configuration ) could be good which can be extended to group of hardware.
> 
>     * Not necessary prior to kubernates provisioned could be case after provisioned also ( for example some time corporate network proxy configuration changes which need to be applied )

I don't want to deviate much from former question, but to my eyes this sounds like a good example for use cases of **fleet + rancher-system-agent** (to apply a plan on certain clusters to all nodes) and **fleet + system-ugrade-controller** (to apply a plan on certain clusters to all nodes with some per node orchestration).

I have not experimented with it myself, but to me feels like it should be possible to set rancher-system-agent plans with fleet with a similar fashion as we do for upgrades.

As @agracey mentioned the elemental-system-agent is stopped as soon as the kubernetes provisioning starts, so the use cases for that should be limited to pre-provisioning kubernetes and post-provisioning elemental-OS. In most cases tweaks and config changes at this stage should be handled with cloud-config data.

**Comment by kkaempf** [comment]
no further updates, closing
