### ISSUE TITLE
Pull base ISO as containers instead of http download

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#396]
Currently the build ISO feature downloads the ISO from an http url within the build environment. That means multiple builds based on the same ISO results into multiple downloads of the same exact bits. In order to improve this I'd suggest to pull the ISO image as a container, as an init continer of the build pod.

Why?

* We can reuse the same pulled image for many machine registrations
* We can easily relay on the same distribution scheme as we have for OS containers (registry and channel concept)
* We relay on kubernetes garbage collector for the cleanup of unused ISOs
* Nothing needs to be downloaded for an ISO rebuild over the same node.

What needs to be changed?

* Adapt current build-iso to include labels and tags as expected and be perfectly aligned with node-image
* Include busybox or similar in containerzied ISO to copy contents to somewhere else
* Adapt elemental operator to pull image and copy container contents instead of downloading from the network
* Include ISO field in ManagedOSVersions to link ISOs with released image?

**Comment by agracey** [comment]
I'm wondering if it might make sense to specify a tag structure convention. So for each OS version (`<image>:myversion`), there's a corresponding image including the ISO image (`<image>:myversion-iso-x86_64`).

**Comment by davidcassany** [comment]
> I'm wondering if it might make sense to specify a tag structure convention. So for each OS version (`<image>:myversion`), there's a corresponding image including the ISO image (`<image>:myversion-iso-x86_64`).

I definitely makes sense to my eyes. This is trivial in OBS as it will keep both perfectly aligned and we can easily normalize names in there.

In any case I would still add a SeedImageURLs field in ManagedOSVersions resource (despite being predictable) because this way we could even consider details like releasing a new OS update without a SeedImage and some OS without ISO but with a disk image, etc. Keeping this flexibility is almost free at this point.

**Comment by agracey** [comment]
> Keeping this flexibility is almost free at this point.

For sure, it just means that we can write higher order automation to help out other places :D
