### ISSUE TITLE
SeedImage API: build a SeedImage builder image in OBS

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#401]
We need to build the new SeedImage builder image in OBS (see #374 ).
We need also to ensure the Elemental operator chart in OBS to point to the SeedImage builder image in OBS once ready.

**Comment by fgiudici** [comment]
OBS PR https://build.opensuse.org/request/show/1076963

**Comment by kkaempf** [comment]
OBS request got accepted last week
