### ISSUE TITLE
operator: pkg util should not write logs

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#425]
The util package is used both in the controllers and in the registration binary.
Not only the logging format differs between the two, but also the severity of the logs may change depending of the context (e.g., the MarshalCloudConfig func logs a *warning* if passed an empty cloud-config: a warning is fine for the registration client, while too much when processing the cloud-config in the seedimage controller).

Move all logging out of the util package (or at the very least, just allow debug logging in the util package).

**Comment by kkaempf** [comment]
fixed in v2
