### ISSUE TITLE
ManagedOSImage with private image registry 

### ISSUE THREAD

**Issue by sudheermygapula** [rancher/elemental-operator#430]
Could see similar issue https://github.com/rancher/system-upgrade-controller/issues/204 

But need more details how  elemental managed os concept works with private registry .   is it possible to define the pull Secrets in ManagedOSImage yaml ?

**Comment by fgiudici** [comment]
Currently pull secrets cannot be defined into the ManagedOSImage yaml nor cannot be configured to allow downloading the base image from an authenticated registry.
This is something we have to address: let's add a specific feature card for this in the airgap epic.

**Comment by kkaempf** [comment]
This is covered by Rancher Manager documentation (airgap). We currently have no plans to support elemental-operator outside of Rancher Manager,
