### ISSUE TITLE
Elemental hosts should run elemental-register at each boot

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#434]
After registration and provisioning, each host should re-register at each reboot.
This would ensure:
1. the host is tracked by a MachineInventory in the Elemental Operator
2. labels and annotations (in particular the IP addr annotation, SMBIOS and HW labels) are updated

Note that point 1. could be useful only if the host has not been made part of a cluster yet, otherwise  the tracked state could be a bit tricky: if the host is already part of a cluster (provisioned with a kubernetes deployment) it cannot be completely re-synced.
This case is *not* part of this card, and should be tracked in a follow-up one.

**Comment by fgiudici** [comment]
Note that re-registering at each boot is incompatible with `emulate-tpm` with random `emulated-tpm-seed` (equal to `-1`').
Hosts configured with random `emulated-tpm-seed` should be prevented from re-registering.

**Comment by kkaempf** [comment]
I don't think we should enable re-registration generally. It's a scalability/bandwidth challenge.

**Comment by kkaempf** [comment]
It's still a scalability challenge. Thinks of thousands of cash registers being turned on when shops open.

**Comment by anmazzotti** [comment]
> It's still a scalability challenge. Thinks of thousands of cash registers being turned on when shops open.

I can add a randomized sleep interval so that we can stagger the registration attempts.  
It's not a proper solution I believe, but maybe a good mitigation.

**Comment by anmazzotti** [comment]
FYI I opened the new follow up issue: #471
Feel free to add notes in case I miss anything.

**Comment by fgiudici** [comment]
Agreed that dealing with re-registrations timings deserves a separate discussion / issue: #471 is perfect for it.
There is one important missing  scenario anyway we should deal with here: deleted MachineInventories which track hosts that will re-register. 
That will cause the MachineInventory to be recreated as a "clean" machine, but that is not the case if the Machine has been already provisioned as part of a Cluster.
It looks to me we should re-register differently than registering, likely we need to extend the registration protocol to be safe. Further discussion needed.
