### ISSUE TITLE
CI: OBS PR workflow keeps failing on images repo building

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#445]
The operator-image and seedimage-builder packages keep failing on the OBS PR workflow:

![image](https://github.com/rancher/elemental-operator/assets/15175304/ff046983-15ec-4a36-a242-1d194183ff6e)

**Comment by kkaempf** [comment]
Did two things
- copied prjconf from the originating project
- added `Prefer: container:suse-sle15-15.4` to resolve the "have choice" situation

Project is building now.
