### ISSUE TITLE
Rancher do not take automatic snapshots of Elemental RKE2 cluster 

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#461]
Rancher version: ?
RKE2 cluster version: v1.25.9+rke2r1

Rancher configured to take automatic snapshots: snapshots for *elemental* RKE2 clusters are not there ("Restore Snapshot" from the Cluster Management Rancher UI doesn't show any available snapshot).

Note that:
- elemental K3s  v1.25.9 clusters have regular snapshots
- *not elemental* RKE2   v1.25.9clusters have regular snapshots

**Comment by kkaempf** [comment]
no longer relevant
