### ISSUE TITLE
Elemental Dashboard (user doesn't have enough permissions or the Elemental Operator is not installed)

### ISSUE THREAD

**Issue by mpas** [rancher/elemental-operator#469]
The following Helm charts have been applied:

- https://github.com/rancher/elemental-operator/tree/v1.2.5/charts/crds
- https://github.com/rancher/elemental-operator/tree/v1.2.5/charts/operator

The Elemental extension in Rancher is installed and pointing towards 1.2.0. 

- Operator is running fine

When navigating to `OS Management` > `Dashboard` in the Rancher server the following message is shown.

![image](https://github.com/rancher/elemental-operator/assets/139094/6702f7af-1be4-4866-ad5a-c26db0f2a484)

- Either the user doesn't have enough permissions to run the OS Management extension or the Elemental Operator is not installed (required to run the OS Management extension).
- For user permissions, check with your Rancher administrator if the correct role is assigned. To install Elemental Operator please follow the instructions on the official [documentation](https://elemental.docs.rancher.com/quickstart-cli#install-elemental-operator).

Everything is installed and running fine so lost on what could be the root cause of this or how to fix it. Could be a bug or a misconfiguration on my end. Any hints on how to solve this would be great!

**Comment by mpas** [comment]
- With regards to the user, which user should that be and what should be the permissions?
- What role should be assigned to the user?

**Comment by fgiudici** [comment]
> * With regards to the user, which user should that be and what should be the permissions?
> * What role should be assigned to the user?

From the Rancher User dashboard, the user should either be granted the _Administrator_ _GlobalPermissions_ (which allows access to all resources in the cluster) or needs to be added also the _Elemental Administrator_ _Custom_ permissions.

Under the hood, the _Elemental Administrator_ _Custom_ permissions creates a GlobalRoleBinding matching the _User_ to the _elemental-operator_ _GlobalRole_ .

**Comment by fgiudici** [comment]
After some testing, cannot find any issue with the permissions to access the Elemental UI.
The default admin is granted the Admin GlobalRole, which allows all the verbs on all the resources on the Cluster.
My best guess is some issues with the the RBAC permissions happened on the Rancher cluster, not related to Elemental installation.
Closing for now, please reopen if needed.

**Comment by bennysp** [comment]
Seeing the same issues even on the admin account.

![image](https://github.com/rancher/elemental-operator/assets/4121872/eed02ce9-0d07-4338-a85e-faa57be246c2)

![image](https://github.com/rancher/elemental-operator/assets/4121872/12467b4a-2b1f-41d3-9450-8cde42bd0409)

I just used the built in Rancher 2.7.5 feature where you click the "Enable" button.

**Comment by fgiudici** [comment]
Hey @bennysp 👋🏼 
 currently besides the Elemental UI extension you can install directly from Rancher UI, you have to install the Elemental operator manually (helm from cli) as detailed in https://elemental.docs.rancher.com/quickstart-ui .
Have you also installed the Elemental Operator and still facing the issue?
