### ISSUE TITLE
Standardize machine identity and machine authentication

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-operator#473]
With the addition of machine re-registration, we opened the problem of identifying "lost" machines, for example when their MachineInventory has been deleted but they keep trying to reconnect to the operator.

From the operator side (and from a system administrator user point of view), it would be great to be able to identify somehow these lost machines. 

Currently we don't have a standard way of identifying a machine and identity is not yet implemented in a standard way. We use TPM and that works, however in absence of TPM we don't have other reliable solutions.

Operator side, it's also difficult to report in a sensible way on machines when errors occur. For example if a machine keeps failing the authentication, how can we identify where this machine is and how to stop it? We provide the TPM hash if any, or the MAC address of the machine if that is used as authentication method, but these identifiers are not human readable and provide little to none useful information.

Regarding authentication, we currently have different authentication methods, but only the TPM one is reliable and uses an additional challenge. It is possible that with the addition of different authenticators, they will diverge more and more in terms of implementation, making it a maintenance challenge.

For this reason we should find a way to: 
- Standardize the initial authentication and provide a consistent way to implement MFA through different challenges (for ex. TPM) 
- Identify machines in a consistent way, no matter what authentication method they are using

For this reason my proposal is to adopt JWT as `Authorization`  bearer token. 
Unsigned JWT can be initially adopted to keep the implementation simple and easy to switch to.

The benefit of using a JWT token is that we can add several claims to help identifying each machine. For example serial number, TPM hash, IP addresses, and any other human readable information that describes "who" this machine claims to be.

The only drawback is that it will considerably expand the token size, however since this is only used once to Upgrade the HTTP connection to websocket, it should be negligible. 

Later on we could provide real authentication by actually signing JWTs. 
One way would be to create/distribute signing keys on each machine, and the operator will just have to validate the JWT for the authentication to succeed.

**Comment by anmazzotti** [comment]
Also note that JWT supports multiple signatures. 
This can be used to protect the registration endpoint too, making it more secure when exposed on a public network.

Each registration could use a different certificate. The certificate key can be distributed with the seedimage so that machines will be able to securely authenticate to the registration endpoint. 

Additionally machines could create their own signing certificate and double sign the JWT. The public key can be stored in the MachineInventory, adding an extra challenge. Note that in this case it would be ideal to be able to update the machine certificate, so that machines can easily implement rotation, for example at each boot during the registration update.

**Comment by kkaempf** [comment]
fixed with CAPI
