### ISSUE TITLE
OS Management option not coming up after elemental 1.2.0 is installed in Rancher 2.7.0

### ISSUE THREAD

**Issue by harsha-vardhan-n** [rancher/elemental-operator#475]
I have setup **Rancher 2.7.0 as a Single Container** and I have installed helm operators and crds as below

`helm_v3 --set httpProxy="http://x.x.x.x:x" --set httpsProxy="http://x.x.x.x:x" --set noProxy="x.x.x.x" upgrade --create-namespace -n cattle-elemental-system --install elemental-operator-crds oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-crds-chart`

`helm_v3 --set httpProxy="http://x.x.x.x:x" --set httpsProxy="http://x.x.x.x:x" --set noProxy="x.x.x.x" upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart`

NAMESPACE                          NAME                                                       READY     STATUS        RESTARTS      AGE
cattle-elemental-system       elemental-operator-5ff9c8cb86-jv6z5     1/1        Running       1 (24m ago)   34m
cattle-fleet-local-system      fleet-agent-7bcc7d69cf-9jtsk                   1/1         Running       1 (24m ago)   79m
cattle-fleet-system               fleet-controller-6b474d95fb-wh4rk         1/1         Running       1 (24m ago)   80m
cattle-fleet-system              gitjob-755ff7984f-xvlmr                             1/1         Running       1 (24m ago)   80m
cattle-system                       helm-operation-4hshg                               0/2        Completed   0                     34m
cattle-system                       helm-operation-8f4kd                                0/2        Completed   0                     50m
cattle-system                       rancher-webhook-5898d78956-qkf74      1/1        Running       1 (24m ago)   79m
cattle-ui-plugin-system     ui-plugin-operator-69cf444c86-w8q5m   1/1        Running       1 (24m ago)   34m
kube-system                       coredns-b96499967-fqv4k                         1/1        Running       1 (24m ago)   81m

Find the screenshots for the same

![image](https://github.com/rancher/elemental-operator/assets/79247762/c5ab5ad9-859b-48ba-8f29-2afba4e3932c)

![image](https://github.com/rancher/elemental-operator/assets/79247762/409263ea-1b35-4a1b-b4ab-cce6b02449df)

**Comment by kkaempf** [comment]
On [Slack](https://rancher-users.slack.com/archives/C028DVCAYLD/p1688571111767909) you said:

~~~
the only error from the pod i get is below,  time="2023-07-05T11:11:39Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.109.133:443: i/o timeout, requeuing"
~~~

which looks like a routing error.

Make sure that your management cluster is able to reach out to the internet, esp. `raw.githubusercontent.com`

**Comment by fgiudici** [comment]
Hey @harsha-vardhan-n , seems the UI plugin installed correctly.
Maybe silly question,  but let's check the basics first:  have youcompletely reload the Rancher dashboard UI from the browser? That is required after a UI plugin is installed.

**Comment by harsha-vardhan-n** [comment]
Hii @fgiudici, Yes i have reload the browser cleared cache also and tried nothing worked.

Infact i even restarted the docker container itself to see if it works but no luck.

Also to provide more info, I have done this setup in a non-proxy environment it worked fine. but this is a proxy restricted environment and i can confirm you that i have set the proxy in docker and i have validated the internet access as well that's the only difference.

**Comment by fgiudici** [comment]
@aalves08 , have you by chance already seen something like this?

**Comment by juadk** [comment]
I'm not sure that's the same with Rancher in docker but when I test Rancher behind a proxy, I install Rancher using Helm with these additional flags:
```
--set proxy="$MY_PROXY_IP:PORT"
--set noProxy="127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local"
```

**Comment by aalves08** [comment]
Hello @harsha-vardhan-n . Where are you getting the `elemental-ui` extension from? Is it from our official extensions repo (https://github.com/rancher/ui-plugin-charts) or the `elemental-ui` repo (https://github.com/rancher/elemental-ui)? It's just that elemental 1.2.0 shouldn't be meant to run on Rancher 2.7.0 (only 2.7.2 and upwards).

https://github.com/rancher/ui-plugin-charts/blob/main/index.yaml#L13

This annotation is missing from the `elemental-ui` repo. 

The second option is that you are using the correct repo (official one) but in 2.7.0 we still didn't have the checks on the UI side to prevent you from using it.

Nevertheless, the elemental extension is only truly supported from 2.7.2 and onwards. Can you spin up a more up-to-date system and try again?

**Comment by harsha-vardhan-n** [comment]
Hi @aalves08,

Fine, let me do that quickly and update you

**Comment by harsha-vardhan-n** [comment]
Hii @aalves08 

As per your suggestion i spin up Rancher 2.7.4 as a Single docker container

Installed crds and operator as below

`helm --set proxy="$MYPROXY:$PORT" --set noProxy="127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.17.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local" upgrade --create-namespace -n cattle-elemental-system --install elemental-operator-crds oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-crds-chart
`

`helm --set proxy="$MYPROXY:$PORT" --set noProxy="127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.17.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local" upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart
`

After this enabled the Rancher Extension and tried to install Elemental but started getting Error "An error occurred loading the code for this Extension"

Below error also coming up in operator pod

`kubectl logs -f ui-plugin-operator-5d68dd4bc9-gj7kk -n cattle-ui-plugin-system --v=9`

time="2023-07-07T09:52:01Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.108.133:443: i/o timeout, requeuing"
time="2023-07-07T09:52:31Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.109.133:443: i/o timeout, requeuing"
time="2023-07-07T09:53:01Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.108.133:443: i/o timeout, requeuing"
time="2023-07-07T09:53:31Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.109.133:443: i/o timeout, requeuing"
time="2023-07-07T09:54:01Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.108.133:443: i/o timeout, requeuing"
time="2023-07-07T09:54:31Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.109.133:443: i/o timeout, requeuing"
time="2023-07-07T09:55:01Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.108.133:443: i/o timeout, requeuing"
time="2023-07-07T09:55:31Z" level=error msg="error syncing 'cattle-ui-plugin-system/elemental': handler on-plugin-change: Get \"https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json\": dial tcp 185.199.109.133:443: i/o timeout, requeuing"

**Comment by aalves08** [comment]
From a UI standpoint, I don't know more to help with you. There's some kind of connection error there, but the assets are accessible. https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json

So, it's either something specific with your setup or something with the operator.

**Comment by harsha-vardhan-n** [comment]
> From a UI standpoint, I don't know more to help with you. There's some kind of connection error there, but the assets are accessible. https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/1.2.0/plugin/package.json
> 
> So, it's either something specific with your setup or something with the operator.

Hello @aalves08 

I have not done anything extra, i am installing in a proxy environment that's the only difference.

I have applied the same procedure in a non-proxy environment and its working fine.

Have you ever tried this in a proxy restricted environment ? did it work any specific settings to be done additionally?

i suspect the extra helm charts we deploy as a pre-requisite for elemental is what requires a specific customization in a proxy environment.

Any more logs I could look at please let me know.

**Comment by aalves08** [comment]
I am sorry @harsha-vardhan-n , but I lack the knowledge to help you here since I am a frontend developer and this is clearly a backend/configuration issue. I would suggest opening up an issue on `rancher/rancher` repository or pose the question on our public slack https://slack.rancher.io/ on the #general channel.

**Comment by harsha-vardhan-n** [comment]
Alright I Finally was able to fix this by setting the proxy for the elemental pod deployment.

the pod created for elemental was not considering the docker set proxy hence needed to set separately and I was able to resolve.

we have to set the proxy after we enable the extension and before the plugin installation.
