### ISSUE TITLE
Force registration update on boot

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-operator#481]
Follow up of #471, to address @davidcassany 's [comment](https://github.com/rancher/elemental-operator/pull/479#discussion_r1266601579).

We implemented a (not modifiable yet) 24 hours timer to update the registration information.
The elemental-register is triggered frequently (at every boot and every 30 minutes after that), however we are skipping updates if the last update was less than 24 hours ago.

Ideally we should run the registration update anyway at every boot, as we have most chances there to have information to update (for example a new device being attached, a new IP address, etc.). 

Even more ideally I'd say we should trigger registration update frequently, but only perform it if we have changes to push.
For this reason I propose we extend the registration state to act as a cache and we force an update any time we actually have changes. This should minimize transactions, we can get rid of the 24 hours timer completely, and rely on systemd timer triggering an attempt at boot and every 30 minutes, should suffice for most use cases.

From @davidcassany other two options come to mind to force updates on boot:
1. We could have a sentinel file that is created on an ephemeral location to validate if this is a reboot or not.
2. We could add an  --install flag in elemental-register to run the installation or not. So the flag is only applied when running from the ISO (still need to figureout how, but there are ways) and this flag is never applied to the service that runs on an installed system. This way the timer can be directly over 24h.

**Comment by anmazzotti** [comment]
Most likely the initial comment is out of date. 
What we can still do here however is to add configuration arguments in the `MachineRegistration` to configure the re-registration behavior. For example `enabled` flag and a timer setting.

**Comment by kkaempf** [comment]
this is done
