### ISSUE TITLE
operator-image is missing certificates

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#483]
(ISO-)image download by elemental-operator might fail with self-signed certificates:
~~~
level=error msg="Failed to dial steve aggregation server: tls: failed to verify certificate: x509: certificate signed by unknown authority"
~~~

Rebuilding the `operator-image` with the ca-certificate packages fixes this error

**Comment by dgiebert** [comment]
Did a successful end-to-end test with the customer for registration, cluster creation, and upgrade :rocket:
