### ISSUE TITLE
[tech debt] Use optimistic locking for the seed image

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#487]
While testing restore and backup we realized a race condition appears. Elemental-operator reconcile loop can be triggered due to restoring a pruned object before the status of this same object is actually restored. That can easily cause inconsistencies like recreating a new machine registration token for a resotred machine registartion object.

One option to solve that is adding optimistic locking in patch operations, to prevent writing a computed status over an outdated resource. The side effect of this approach is that the resource object and its status subobject can't be both modified within the same loop (at least with our current reconcile pattern) and this impacts, at least, the retrigger flag of the seed image resource. In order to make use of optimistic locking in seed image resources we need to either modify our current patch logic to explore updating status and its parent resource in a single loop or either refactor the internal contoller logic to always update parent and child resources in different loops.

Seen as part of #486

**Comment by kkaempf** [comment]
not planned
