### ISSUE TITLE
Normalize and automate channel generation

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#511]
Channels are currently created manually directly in OBS, however they are starting to be tightly coupled with elemental-operator releases. Basically each elemental-operator release points to an specific version of the channel, in fact they currently share the version numbering. So elemental-operator v1.3.3 pulls channel v1.3.3.

Given this relationship I suggest to include channel image sources within the `elemental-operator` repository and include a helper script to keep generate its json contents by appending new versions based on released tags.

This would help to sync the Dockerfile entirely with a _service file on elemental-operator. Json contents would still be manually updated but it could be scripted by just providing heading image or by increasing old releases.

Alternatively we could consider a dedicated repository with the benefit of being capable to commit to the channel without having to commit (and eventually tag) elemental-operator repository. In that case we could also consider some sort of automated validation to make sure channel is in sync.

**Comment by davidcassany** [comment]
I have done a first iteration of this task here https://build.opensuse.org/request/show/1111998

It does not add the channel into a repository (dedicated or elemental-operator) but it keeps track of the elemental-operator version and elemental-teal version being build within the same project in OBS. Hence it consistently sets the version of the teal image to the tag of `node-image` and it also sets the channel image tag to the version of the elemental-operator being build within the project.

I consider this a decent trade off in order to prevent mis-aligned tags in Staging builds. We can further elaborate if pushing the channel to a git repository is actually needed. 

Appending released images within the channel.json file would still be a manual process. Trying to automate such a process seams too convoluted IMHO.

**Comment by kkaempf** [comment]
Accepted for `Dev` but `containers_next` needs fixing :wink:

**Comment by davidcassany** [comment]
> Accepted for `Dev` but `containers_next` needs fixing 😉

Indeed, I have not considered `containers_next` because we still miss a versioning scheme for SLE Micro 4 Rancher based images. `RELEASE` or `latest` are not applicable, `latest` usage is discouraged (and forbidden in marketplace) and `RELEASE` can't be known before hand, so not really useful for development or testing.

Versioning of the upcoming images is something to discuss.

**Comment by kkaempf** [comment]
mostly fixed, closing
