### ISSUE TITLE
Support patching (and deleting) managedOSVersions form channel

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#513]
Currently, if a channel update returns a managed OS version that was already loaded it is not patched. It turns to be handy having a `latest` managed OS version pointing to the latest available image. This way in the UI there is a `latest` version that actually points to a numbered version. Consider a channel including:

```json
[
  {
    "metadata": {
      "name": "latest"
    },
    "spec": {
      "version": "v1.2.2",
      "type": "container",
      "metadata": {
        "upgradeImage": "%%IMG_REPO%%/rancher/elemental-teal/%%SLEMICRO_VERSION%%:1.2.2",
        "displayName": "Elemental Teal OS"
      }
    }
  },
  {
    "metadata": {
      "name": "v1.2.2"
    },
    "spec": {
      "version": "v1.2.2",
      "type": "container",
      "metadata": {
        "upgradeImage": "%%IMG_REPO%%/rancher/elemental-teal/%%SLEMICRO_VERSION%%:1.2.2",
        "displayName": "Elemental Teal OS"
      }
    }
  }
]
```

So there are two managed OS versions pointing to the same image. The channel is upgraded and provides further versions and then latest points to a different version the underlaying ManagedOSVersion for latest won't be updated, as the channel controller does not patch managed os versions.

In addition if some images are removed (or deprecated) from the channel because the underlying OS is no longer supported this information should be also synched in some way to already existing deployments.

**Comment by anmazzotti** [comment]
Just throwing the idea out there. 
What if we have the ManagedOSVersion resource define a `source` optional field where to define a container as we do currently, but also have a field `versions` that is an array of OSVersions? The array should override whatever is included from the source container.

The intended use is that as admin I can:
- Rely on the Elemental official shipped source and call it a day
- Rely on the Elemental official shipped source, but override one or more official versions to deprecate them, or create new versions and reference my own built containers
- Create my own source container and rely on that. (This would be ideal in airgap scenarios I believe)

**Comment by davidcassany** [comment]
I am not sure, basically the change suggests making the list of images as part of a resource rather than listing resources. Like making the channel containing the list of images rather than providing the assets to generate new child resources.

Beyond the fact this would be a behavior and API change that is also likely to impact the UI I struggle to see what would this enable that is currently not possible apart from dropping/hiding previously announced versions. Current approach might require some more logic but I think it is quite flexible and allows versions listing in a highly customizable fashion.
