### ISSUE TITLE
elemental-operator hangs after setting labels

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#54]
`system-agent` calls elemental-operator as
```
elemental-operator register --label \"elemental.cattle.io/ExternalIP=$(hostname -I | awk '{print $1}')\" --label \"elemental.cattle.io/InternalIP=$(hostname -I | awk '{print $2}')\"
```

This results in respective labels to be added to `machineInventory` (good!), it also makes `elemental-operator` hang indefinitely (bad)

elemental-operator should, when called with `--label` _only_ set labels and not try to call `elemental install`.
It also should return immediately after setting the labels.

**Comment by davidcassany** [comment]
I am havig a look
