### ISSUE TITLE
Add repository concept to OS channels

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#549]
I believe it makes sense having an editable repository in our channels. I'd do something really simple.

If the channel lists images without fully qualified and repository and the channel includes a non empty repository I would prepend the given repository to the generated managedOSVersions image references. For instance a channel with a repository set to `my.airgap.repository.com` and the channel lists versions like:

```
rancher/elemental-teal/5.4:1.2.3
rancher/elemental-teal/5.3:1.1.5
registry.suse.com/rancher/elemental-teal/5.3:1.1.4
```

I woud create managedOSVersions with the following URLs:

```
my.airgap.repository.com/rancher/elemental-teal/5.4:1.2.3
my.airgap.repository.com/rancher/elemental-teal/5.3:1.1.5
registry.suse.com/rancher/elemental-teal/5.3:1.1.4
```

And in general we should not list images with full URLs in channels and relay on channels repository. This would make airgap story easier IMHO. Note that with the current setup, updating he channel repoistory would automatically also update the synched managedOSVersions.

**Comment by fgiudici** [comment]
We are now moving to multi-channel support as a de-facto standard, decoupling the channel release from the operator release.
This should make even easier adding a repository in the ManagedOSVersionChannels (if it is specified, it is applied to *all* the urls, images from different repo should belong to a different ManagedOSVersionChannel).

**Comment by fgiudici** [comment]
This would make the airgap story easier... almost a breeze wrt what we have right now, since the hardest part is to re-construct the ManagedOSVersionChannel, this way one should only copy the OS images to the registry.
