### ISSUE TITLE
Wrong filename in serv container of SeedImage pod

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#555]
In CI and manual tests the `SeedImage` pod fails with this error in the `serve` container:
```sh
# kubectl -n fleet-default logs seed-image-master-cluster-k3s serve
2023/10/26 07:24:49 stat elemental-machine-registration-master-cluster-k3s-2023-10-26T07:24:47Z.iso: no such file or directory
```

According to the logs of the `build` container all looks fine:
```sh
# kubectl -n fleet-default logs seed-image-master-cluster-k3s build
xorriso 1.5.6 : RockRidge filesystem manipulator, libburnia project.

xorriso : NOTE : Loading ISO image tree from LBA 0
xorriso : UPDATE :      14 nodes read in 1 seconds
[...]
xorriso : UPDATE : Writing:      57344s   13.5%   fifo 100%  buf  50%
xorriso : UPDATE : Writing:     376832s   88.8%   fifo 100%  buf  50%  471.9xD 
ISO image produced: 424245 sectors
Written to medium : 424400 sectors at LBA 48
Writing to '/iso/elemental-machine-registration-master-cluster-k3s-2023-10-26T07:24:02Z.iso' completed successfully.
```

But if you check carefully you can see that the filename is different in each containers, it ended with `-2023-10-26T07:24:02Z.iso` for the one in `build` and with `-2023-10-26T07:24:47Z.iso` for the one in `serve`.

According to PR #542 it seems that the `ConfigMap` is generated for each container but in that case the `isoName` seems to be re-generated each time (just an an assumption on my side).

**Comment by frelon** [comment]
Unable to replicate, but I will guess that the reconcile changes the output-name configMap and the pod is not picking up the change.

I put up #556 to try to fix this.
