### ISSUE TITLE
Metrics endpoint for operator pod

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#6]
It would be very helpful to expose some basic counters to a Prometheus (or OpenTelemetry) collector. 

Some potential metrics off the top of my head:

- Basic request latencies and active connections
- Count of MachineInventory with labels
- Count of MachineInventory without labels
- Total count of machines registered ever (re-registrations count should double count)
- Count of machines for each OS image tags
- Average Time between onboarding machine and it's registration into a cluster

**Comment by kkaempf** [comment]
not relevant
