### ISSUE TITLE
Use coud-init files instead of a unit service file for elemental-operator

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#62]
Elemental-operator is called by an `elemental-operator.service` file included into the Elemental OS. From #50 investigations it looks like this has some potential to collide with other on going services. More specific it seams to have issues when executed before `cos-setup-network.service` ends (which happens like one or two minutes after reaching the login prompt). I am wondering if shouldn't we relay on calling `elemental-operator` from one of our yip stages (`network.after`?) for a more cloud-init centric and simpler boot process management. This could be extensible to other one shot services too, if any.

This is also to prevent having to run changes such as https://build.opensuse.org/request/show/990272 which are not obvious.

**Comment by Itxaka** [comment]
This seems to plug in in the rework Im doing of the base elemental (read non OBS tweaked) so I migth just plug this in as part of that card. I mean, I need it to work as close as obs elemental so we can test as close as obs elemental so....

**Comment by davidcassany** [comment]
Completed by rancher/elemental#178
