### ISSUE TITLE
Unable to restore from backup

### ISSUE THREAD

**Issue by SanekP** [rancher/elemental-operator#620]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Spin-up new management cluster: docker run --privileged -d --name rancher -p 443:443 rancher/rancher
- Install Elemental stuff
- Build and download image
- Provision some machine with that image
- Create Elemental downstream cluster
- Add there some workload and check that everything are OK
- Install on management cluster Rancher Backups v103.0.0+up4.0.0
- Create backup
- Stop and remove management cluster
- Spin-up new management cluster: docker run --privileged -d --name rancher -p 443:443 rancher/rancher
- Install Elemental stuff
- Install on management cluster Rancher Backups v103.0.0+up4.0.0
- Restore from backup
- Got an error "Error restoring cluster-scoped resources, check logs for exact error". No MachineInventory, no downstream cluster.

**What did you expect to happen:**
I expect to get same management cluster with MachineInventory and downstream cluster as it was during backup.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
docker exec rancher kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
INFO[2024/02/10 16:39:15] restoreResource: Restoring c-m-hxhw7j5p of type /v1, Resource=namespaces
ERRO[2024/02/10 16:39:15] Error restoring resource c-m-hxhw7j5p of type /v1, Resource=namespaces: restoreResource: err updating resource Namespace "c-m-hxhw7j5p" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"controller.cattle.io/namespace-auth"}
..
INFO[2024/02/10 16:39:16] Processing controllerRef apps/v1/deployments/rancher
INFO[2024/02/10 16:39:16] Error getting object for controllerRef apps/v1/deployments/rancher: deployments.apps "rancher" not found
ERRO[2024/02/10 16:39:16] Error restoring cluster-scoped resources [error restoring c-m-hxhw7j5p of type /v1, Resource=namespaces: restoreResource: err updating resource Namespace "c-m-hxhw7j5p" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"controller.cattle.io/namespace-auth"}]
ERRO[2024/02/10 16:39:16] error syncing 'restore-zwpw5': handler restore: error restoring cluster-scoped resources, check logs for exact error, requeuing
Full [rancher-backup.log](https://github.com/rancher/elemental-operator/files/14229914/rancher-backup.log)

kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n c-m-hxhw7j5p
NAME                                                                               AGE
clusterroletemplatebinding.management.cattle.io/c-m-hxhw7j5p-fleet-default-owner   56m
clusterroletemplatebinding.management.cattle.io/u-bod2esbc6z-admin                 56m
NAME                                   AGE
project.management.cattle.io/p-8qvsc   56m
project.management.cattle.io/p-wdr7h   56m

**Environment:**

- Rancher 
version:
Rancher	v2.8.2
Dashboard	v2.8.0
Helm	v2.16.8-rancher2
Machine	v0.15.0-rancher106
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6+k3s1", GitCommit:"bd04941a294793ec92e8703d5e5da14107902e88", GitTreeState:"clean", BuildDate:"2023-09-20T23:05:58Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6+k3s1", GitCommit:"bd04941a294793ec92e8703d5e5da14107902e88", GitTreeState:"clean", BuildDate:"2023-09-20T23:05:58Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.

**Comment by SanekP** [comment]
Have no idea what this namespace is and why backup-operator deletes it. I tired to delete stuck resources inside this namespace, but backup-operator create another namespace with prefix c-m- and fails with same error.

**Comment by ldevulder** [comment]
Hello @SanekP! Thanks for your report, I'm doing QA for Elemental, I will try to reproduce your issue but it seems that you installed Rancher Manager through Docker and according to the docs you have to follow these [steps](https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-docker-installed-rancher) to backup a rancher server and these [ones](https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-docker-installed-rancher) to restore it.

Did you tried?

**Comment by SanekP** [comment]
Looks like you are right. Just tried to backup & restore new cluster without Elemental and got next:
INFO[2024/02/12 17:52:16] Marking resource projects.management.cattle.io#v3/local/p-sjvvt for deletion 
ERRO[2024/02/12 17:52:16] Error pruning resources: [admission webhook "rancher.cattle.io.projects.management.cattle.io" denied the request: System Project cannot be deleted] 
2024-02-12T17:52:16.891561589Z INFO[2024/02/12 17:52:16] Will retry pruning resources by removing finalizers in 10s 
INFO[2024/02/12 17:52:26] Retrying pruning resources by removing finalizers 
INFO[2024/02/12 17:52:26] Processing controllerRef apps/v1/deployments/rancher 
INFO[2024/02/12 17:52:26] Error getting object for controllerRef apps/v1/deployments/rancher: deployments.apps "rancher" not found 
ERRO[2024/02/12 17:52:26] error syncing 'restore-blt2f': handler restore: error pruning during restore: [admission webhook "rancher.cattle.io.projects.management.cattle.io" denied the request: System Project cannot be deleted], requeuing 


I thought that "docker" instruction made for the sake of simplicity when you don't need backup-operator and can just save all files. But the result archive have size of 2.8GB compare to 1.5MB file from backup-operator.

I'd like to backup only manifest files. So is it possible to migrate all inventory and downstream clusters to other rancher?

**Comment by ldevulder** [comment]
@SanekP sorry for the late reply.

I re-tested cluster migration, without docker so with `rancher-backup-operator`, and it works well with Elemental.
The only things is that apart from the docker stuff, if I follow your steps it will not work as you installed Elemental stuff - and also Rancher Manager - before the restore and this will not work at all!
Please follow the correct procedure to do it: https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.


> I'd like to backup only manifest files. So is it possible to migrate all inventory and downstream clusters to other rancher?

I don't know this, I'm not a Rancher Manager expert and this is not related to Elemental. I saw that you already opened an issue in `rancher-backup-operator` repository, so this is the good place I think.

I will close this issue. Feel free to re-open or open a new one if you have new Elemental issues ;-)
