### ISSUE TITLE
elemental-register-install does not start in airgap mode

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#627]
Finally, I found why airgap works well with stable/staging, and not with dev...

There is a change in the `elemental-register-install`
In dev, we can see a new condition:
```
Wants=time-sync.target
After=time-sync.target
```
In airgap, the system can not reach ntp so elemental-register-install is never triggered:
```
Feb 13 09:02:25 node-002 systemd-timesyncd[1184]: Timed out waiting for reply from 216.229.4.66:123 (0.suse.pool.ntp.org).
Feb 13 09:02:36 node-002 systemd-timesyncd[1184]: Timed out waiting for reply from 162.159.200.123:123 (0.suse.pool.ntp.org).
Feb 13 09:02:46 node-002 systemd-timesyncd[1184]: Timed out waiting for reply from 208.113.130.146:123 (0.suse.pool.ntp.org).
Feb 13 09:02:56 node-002 systemd-timesyncd[1184]: Timed out waiting for reply from 44.190.40.123:123 (0.suse.pool.ntp.org).
Feb 13 09:03:06 node-002 systemd-timesyncd[1184]: Timed out waiting for reply from 96.126.122.39:123 (1.suse.pool.ntp.org).
```

I just deployed a staging env and I confirm that the `time-sync` condition is not there.

## Env: 
rancher: `v2.8.2`
elemental-operator: `dev`

**Comment by frelon** [comment]
Those conditions were added to make `elemental-register-install` work on raspberry pi with disk images. Would it be possible to add an ntp server to the airgap test?

**Comment by fgiudici** [comment]
> Those conditions were added to make `elemental-register-install` work on raspberry pi with disk images. Would it be possible to add an ntp server to the airgap test?

🤔  we cannot assume to have a ntp server in the airgap scenario: an airgap environment does not have access outside the local network. It would be weird to have a local ntp server as an hard requirement for airgap users.

**Comment by frelon** [comment]
If you are using kubernetes you are going to need time-sync one way or another, not sure how to get around that :thinking:

**Comment by davidcassany** [comment]
> > Those conditions were added to make `elemental-register-install` work on raspberry pi with disk images. Would it be possible to add an ntp server to the airgap test?
> 
> 🤔 we cannot assume to have a ntp server in the airgap scenario: an airgap environment does not have access outside the local network. It would be weird to have a local ntp server as an hard requirement for airgap users.

I agree, we cannot assume a ntrp server. However the ntp server was not required, just _wanted_. I guess we need to better configure our services here. From elemental-register PoV I see no issue on scheduling it after `time-sync.target` but is should not be stuck waiting for it. I wonder if there is a way to timeout wanted units.

**Comment by frelon** [comment]
Seems like there is also a `time-set.target` which might be worth experimenting with.

**Comment by frelon** [comment]
> > > Those conditions were added to make `elemental-register-install` work on raspberry pi with disk images. Would it be possible to add an ntp server to the airgap test?
> 
> > 
> 
> > 🤔 we cannot assume to have a ntp server in the airgap scenario: an airgap environment does not have access outside the local network. It would be weird to have a local ntp server as an hard requirement for airgap users.
> 
> 
> 
> I agree, we cannot assume a ntrp server. However the ntp server was not required, just _wanted_. I guess we need to better configure our services here. From elemental-register PoV I see no issue on scheduling it after `time-sync.target` but is should not be stuck waiting for it. I wonder if there is a way to timeout wanted units.

Why not? Kubernetes does not work without synchronized time and any airgap installation will need a local ntp. This would also be a good test of setting a custom ntp server using yip/cloud-config.

**Comment by juadk** [comment]
That's weird because the test is working without ntp configured with stable/stating operator. The 3 nodes kubernetes is working well, we can check the logs to see if it complains.

**Comment by frelon** [comment]
> That's weird because the test is working without ntp configured with stable/stating operator. The 3 nodes kubernetes is working well, we can check the logs to see if it complains.

It works until the time drifts enough. Also since we are using vms the time is probably already synchronized from the hypervisor for all the nodes.

**Comment by ldevulder** [comment]
I just fixed other issues in the airgap test but I'm now again encounter the `time-sync` dependency issue... Could it be possible to set the `Wants` on `time-set.target` instead of `time-sync.target`? As the set action is working this could "fix" our deployment issue.

I agree that time synchronization is a "must have" for Kubernetes but I think that for Elemental we should avoid blocking installation because of this. In case of big issue within a customer env we can still answered that they are are not in a supported configuration I think. But there can be lot of reason why they will be in that situation IMO.

**Comment by ldevulder** [comment]
> It works until the time drifts enough. Also since we are using vms the time is probably already synchronized from the hypervisor for all the nodes.

Yes in our case on VM is already "automatically" done, and this is also a point: customers can use VM and in that case don't want to bother with time-sync on all VM if it's already done on the hypervisor.
