### ISSUE TITLE
Wrong URI set after operator upgrade in ManagedOSVersions

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#629]
The URI in `ManagedOSVersions` for ISO v2.0.2 is set to an older version (v1.1.5) after upgrading the Elemental operator from Stable version (v1.4.2) to the Dev one (v1.5.0):
![Screenshot from 2024-02-15 15-11-06](https://github.com/rancher/elemental-operator/assets/25102165/23e2a935-9b77-4aa2-a727-796f1d13e60e)

**NOTES:**
- Only the ISO is impacted, not the container version!
- It happens only with `RKE2` not with `K3s`! But I really don't know why...

**How to reproduce:**
- Install RKE2 (I used version `1.26.10+rke2r2`, not K3s!)
- Install Rancher Manager Stable (version `2.8.2`)
- Install Elemental operator Stable (version `1.4.2`)
- Check `ManagedOSVersion` for `v2.0.2-iso`, you should have the correct version:
```yaml
# kubectl -n fleet-default get ManagedOSVersions v2.0.2-iso -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  creationTimestamp: "2024-02-15T14:43:43Z"
  generation: 7
  labels:
    elemental.cattle.io/channel: elemental-channel
  name: v2.0.2-iso
  namespace: fleet-default
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: ManagedOSVersionChannel
    name: elemental-channel
    uid: 2a22d089-18b3-4754-b458-6fb4a47fe227
  resourceVersion: "8225"
  uid: 179c6b08-fcb9-4590-9d88-4695182724e1
spec:
  metadata:
    displayName: SLE Micro ISO x86_64
    upgradeImage: registry.suse.com/suse/sle-micro-iso/5.5:2.0.2
  type: iso
  version: v2.0.2
```
- Upgrade Elemental operator to Dev (version `1.5.01)
- Check `ManagedOSVersion` for `v2.0.2-iso` after upgrade, you should have the wrong version:
```yaml
# apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  creationTimestamp: "2024-02-15T14:43:43Z"
  generation: 7
  labels:
    elemental.cattle.io/channel: elemental-channel
  name: v2.0.2-iso
  namespace: fleet-default
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: ManagedOSVersionChannel
    name: elemental-channel
    uid: 2a22d089-18b3-4754-b458-6fb4a47fe227
  resourceVersion: "8225"
  uid: 179c6b08-fcb9-4590-9d88-4695182724e1
spec:
  metadata:
    displayName: Elemental Teal ISO x86_64
    uri: registry.suse.com/rancher/elemental-teal-iso/5.3:1.1.5
  type: iso
  version: v1.1.5
```

I'm able to reproduce it on every try. Let me know if you need more logs.

**Comment by davidcassany** [comment]
I might be a bug in elemental-operator synchronization logic... I am thinking on probably some misused pointer while updating managed OS versions from channel.

I wonder if this [SR](https://build.opensuse.org/request/show/1146906) will have impact somehow to this issue 🤔

**Comment by ldevulder** [comment]
> I wonder if this [SR](https://build.opensuse.org/request/show/1146906) will have impact somehow to this issue 🤔

Having v2.0.2 hardcoded should do the trick I think. I will give it a try tomorrow (let's wait for all syncs to be done before ;-)).

**Comment by ldevulder** [comment]
> Having v2.0.2 hardcoded should do the trick I think. I will give it a try tomorrow.

No change with the mentioned OBS SR.

**Comment by davidcassany** [comment]
I can confirm this issue on stable and can consistently reproduce it on stable elemental versions.

After as successful sync and having all values as expected removing an OSVersion and triggering a sync again causes a weird behavior in which all versions from the channel are used to patch over and over the first already existing ManagedOSVersion listed by runtime controller client.

Need to further investigate in Dev, seams that the issue there might be harder to reproduce as on my first attempt with the described process I could not reproduce it, however it follows the same logic, no changes in that area.
