### ISSUE TITLE
elemental-operator register --label "..." hangs 

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#63]
While setting labels at installation time works (see https://github.com/rancher/elemental-operator/blob/489d40f275abf9aef86d01cfd224cf4ba00c5e97/pkg/controllers/machineinventoryselector/bootstrap.go#L131), I can't get a similar 
`elemental-operator register --label "..."` call to work in the installed system.

All I see is the operator version and the (correct) tom hash with its `wss://...` url and then `elemental-operator` just hangs.

**Comment by kkaempf** [comment]
> I don't see it hanging however I can't get it to work on the installed system mostly because the registration yaml consumed by the `elemental-operator register` is no longer there. Without a registration url it does nothing, not even `exit 1`, I am not sure if this the best behavior but I can't see anything wrong with it.

See #68 why it should be more verbose. 😉 

Where would I find the registration yaml in an installed system ?
We need to manipulate the machineInventory labels later and I hoped `elemental-operator register --label...` would give us this functionality.

**Comment by kkaempf** [comment]
> as we could use `elemental-operator register` not only to install the OS.

👍🏻 👍🏻 👍🏻

**Comment by davidcassany** [comment]
Closing this one since #68 targets the same and it is more precise about the silent or even broken execution paths.

Also by #71 now calling `elemental-operator register --label <somelabel> /oem/registration` on the installed system allows to set labels into the machine inventory.
