### ISSUE TITLE
[Registration] Allow to configure how frequently elemental-register refresh the MachineInventory data

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#641]
Currently, the elemental-register command [is triggered every 30 minutes by a systemd timer](https://github.com/rancher/elemental/blob/v2.0.2/framework/files/usr/lib/systemd/system/elemental-register.timer).
It could be handy to allow to customize the timer for scenarios where the access to the Rancher cluster could be costly (or not always available).

**Comment by kkaempf** [comment]
Not relevant.
