### ISSUE TITLE
raw image does not boot

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#653]
I was trying to automate the raw image test and I figured out that the raw image does not work on my NUC:

![image](https://github.com/rancher/elemental-operator/assets/6025636/4dfab9b5-93e0-4551-a4ef-6df321ec74da)

We also hit this issue with virtualization on OpenSuse 15.5, however, I can boot it without any issue on my arch system...

## Machine registration used:
```
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  creationTimestamp: "2024-02-29T09:10:02Z"
  generation: 1
  name: myreg
  namespace: fleet-default
  resourceVersion: "22459"
  uid: 17230953-f1ba-4439-8678-cf07800d93a6
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        debug: true
        device-selector:
        - key: Name
          operator: In
          values:
          - /dev/sda
          - /dev/vda
          - /dev/nvme0
          - /dev/mmcblk0
          - /dev/nvme0n1
        poweroff: true
      reset:
        debug: true
        enabled: true
        poweroff: false
        reboot: true
        reset-oem: true
        reset-persistent: true
  machineInventoryAnnotations:
    myInvAnnotation1: myInvAnnotationValue1
  machineInventoryLabels:
    CPUModel: ${System Data/CPU/Model}
    CPUVendor: ${System Data/CPU/Vendor}
    CPUVendorTotalCPUCores: ${System Data/CPU/Total Cores}
    NumberBlockDevices: ${System Data/Block Devices/Number Devices}
    NumberNetInterface: ${System Data/Network/Number Interfaces}
    TotalCPUThread: ${System Data/CPU/Total Threads}
    TotalMemory: ${System Data/Memory/Total Physical Bytes}
    myInvLabel1: myInvLabelValue1
  machineName: ${System Data/Runtime/Hostname}
status:
  conditions:
  - lastTransitionTime: "2024-02-29T09:10:02Z"
    message: ""
    reason: SuccessfullyCreated
    status: "True"
    type: Ready
  registrationToken: x92pfklhwjg9fzbdzrcs5fr56glgg8jh5txvqtzslvfhrgqr5js5lw
  registrationURL: https://rancher.164.92.202.119.sslip.io/elemental/registration/x92pfklhwjg9fzbdzrcs5fr56glgg8jh5txvqtzslvfhrgqr5js5lw
  serviceAccountRef:
    kind: ServiceAccount
    name: myreg
    namespace: fleet-default
```

## Elemental operator
Operator version 1.5.0, architecture amd64, commit 48da810b, commit date 20240226

**Comment by frelon** [comment]
@juadk Is secure boot enabled? Our use of squashfs for the recovery system might not be working with secure-boot until https://github.com/rancher/elemental-toolkit/pull/1975 is merged.

**Comment by juadk** [comment]
> @juadk Is secure boot enabled? Our use of squashfs for the recovery system might not be working with secure-boot until [rancher/elemental-toolkit#1975](https://github.com/rancher/elemental-toolkit/pull/1975) is merged.

I tested with secure boot enabled from my side but @ldevulder tested it without and he hit the same issue.

**Comment by juadk** [comment]
This is not supported to boot through USB stick with raw image and expect installation on HDD.
