### ISSUE TITLE
Update fleet and system-upgrade-controller APIs

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-operator#672]
For the system-upgrade-controller, the API used is 2 years old. 
I believe it's safe to update to the newer version.  Probably worth to double check if there are any breaking changes.

When it comes to fleet, the same applies. 
This is probably a good occasion to get rid of the custom wrapper, since it feels unnecessary: https://github.com/rancher/elemental-operator/blob/main/api/v1beta1/managedosimage_types.go#L65

Version 0.8 of Fleet introduced the `doNotDeploy` [target option](https://fleet.rancher.io/0.8/ref-crds#bundletarget) which is pretty interesting and could also be exposed on the `ManagedOSImage` so that some clusters could be filtered out of upgrades.

**Comment by anmazzotti** [comment]
system-upgrade-controller API can be upgraded without issues

Fleet API on the other hand has some troubles.
New Fleet API requires Wrangler v2 and from there on it's only troubles.

This is probably not as easy task as I thought.

**Comment by kkaempf** [comment]
[Fleet 0.10](https://github.com/rancher/fleet/releases/tag/v0.10.0-rc.4) should have dropped wrangler.

**Comment by anmazzotti** [comment]
In favor of Wrangler v2 :( https://github.com/rancher/fleet/blob/v0.10.0-rc.4/go.mod#L34
