### ISSUE TITLE
use harvester-friendly image URL 

### ISSUE THREAD

**Issue by nnewc** [rancher/elemental-operator#673]
I want to be able to deploy seed images built in elemental-operator to Harvester. Currently I have to download the image locally and upload to harvester. It would be nice to paste the image URL from the image manifest directly into harvester. This also could be used with automation like Terraform. 

Currently, elemental-operator does not append a file extension. This is just requesting a harvester supported extension be added the end of the URL. 

<img width="988" alt="image" src="https://github.com/rancher/elemental-operator/assets/76885214/d4393c8f-738a-46ed-b0b2-e053f950fb63">

**Comment by fgiudici** [comment]
Well, the file name is passed in a "Content-Disposition" header, which is honored by the browsers and by wget --content-disposition. 
Yes, looks good to me to append to the download url something like that @frelon 👍🏼
