### ISSUE TITLE
Include elemental-operator related images into rancher security radar

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#688]
We should provide a list of elemental images. I'd assume this is the same list of images that is used for airgap. We could do something similar to https://github.com/rancher/rancher/releases/download/v2.8.2/rancher-images.txt

**Comment by davidcassany** [comment]
Hi @pjbgf,
Just added an `elemental-operator-images.txt` file listing all images referenced with the chart in current supported releases (v1.3.5, v1.4.2 and v1.4.3). See the latest one as an example https://github.com/rancher/elemental-operator/releases/download/v1.4.3/elemental-operator-images.txt 

Does it match what you'd expect and need to run security scans on elemental image releases?

**Comment by pjbgf** [comment]
@davidcassany that looks good and inline with what we consume from other projects. Thank you for working on this. :bow: 

cc: @rancher/rancher-security
