### ISSUE TITLE
Include elemental-operator version into an annotation in elemental-operator deployment resource

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#691]
The idea is to include the elemental-operator version in an annotation within the deployment. This will easily allow the UI to actually react according to the elemental-operator version. 

With @aalves08 we agreed to map features to versions in UI, hence if the elemental-operator is not in the version including certain feature this will not show up in the UI.

Currently for elemental-operator v1.5.x we included a couple of features impacting UI:
* Raw disk images can only be built using the UI starting from elemental-operator v1.5.x
* The machine registration defaults in latest UI RC are only supported for v1.5.x and onwards. Basically the snapshotter related defaults. On previous versions the defaults should *not* include the snapshotter field.

**Comment by fgiudici** [comment]
The idea is to use the [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) for the `deployment` resource
