### ISSUE TITLE
Split elemental-operator server and client side in two different binaries

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#72]
This card is to strip `elemental-operator register` subcommand into its own binary. Server side is installed in management cluster via a helm chart. The client side is something to include in elemental nodes OS to ensure they can eventually register and bootstrap, hence all the controller logic is not needed for nodes.

**Comment by Itxaka** [comment]
This is about generating 2 binaries from the SAME repo rigth? Not separating the code into its own?

**Comment by davidcassany** [comment]
> This is about generating 2 binaries from the SAME repo rigth? Not separating the code into its own?

Exactly, this is about building two binaries out of the same repository. So creating its own main for `elemental-operator register` I am also not about which name should it have, probably `elemental-register`? `elemental-operator-cli`? binary should be called different to avoid confusion and to allow a co-installation of both.

**Comment by Itxaka** [comment]
nice, on it, this should be pretty straightforward

**Comment by Itxaka** [comment]
Done, now we generate 2 different binaries on release cut and 2 different docker images with its own binaries on them so they can be used by any builders.

**Comment by Itxaka** [comment]
@kkaempf This does affect OBS :D
