### ISSUE TITLE
Actions not covered by new allowed rule

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-operator#724]
Taking a quick look through the actions used in this repo vs what will be [allowed](https://github.com/rancher/security-team/blob/main/docs/rancher-gha-standards.md#allowed-github-actions) we have the following actions that we will have to either replace or allow:

- [x] mikefarah/yq@v4.28.2 .github/actions/chart/action.yaml
- [x] mikefarah/yq@v4.28.2 .github/workflows/airgap-test.yaml 
- [x] helm/kind-action@v1   .github/workflows/e2e.yaml
- [x] ncipollo/release-action@v1 .github/workflows/release-chart.yaml
- [x] codecov/codecov-action@v4 .github/workflows/unit-tests.yaml

**Comment by anmazzotti** [comment]
Seems that everything under `helm/` got approved: https://github.com/rancher/security-team/issues/738#issuecomment-2110440742

**Comment by anmazzotti** [comment]
Codecov still under evaluation: https://github.com/rancher/security-team/issues/728

I'd keep it meanwhile since I think it's pretty useful.

**Comment by anmazzotti** [comment]
Codecov action is approved, but the feedback is quite negative. 
Probably it's for the best to remove it to avoid issues in the future:
- https://github.com/rancher-sandbox/cluster-api-provider-elemental/pull/57
- https://github.com/rancher/elemental-operator/pull/738

**Comment by anmazzotti** [comment]
All good now, closing this issue.
