### ISSUE TITLE
Reconsider release strategy of elemental-operator and elemental-channel

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#727]
Elemental channels require some rethinking:
* Define versioning and what to include in them
* Define desirable automation (e.g. based on OS rebuilds)
* Define the relation within Elemental-operator releases

Consider the relation of elemental-operator with the OS build stack:
* How it relates the supportability?

**Comment by anmazzotti** [comment]
Progress on this epic:

- Channels automation is [done](https://github.com/rancher-sandbox/elemental-channels).
- https://github.com/rancher/elemental-operator/pull/750 (+ 1.6.x backport https://github.com/rancher/elemental-operator/pull/752)

Still to do:
- https://github.com/rancherlabs/eio/issues/2388
- https://github.com/rancher/elemental/issues/1462
- https://github.com/rancher/elemental-ui/issues/183

Nice to have:
- https://github.com/rancher/elemental-operator/issues/759
- https://github.com/rancher/elemental-operator/issues/760

**Comment by anmazzotti** [comment]
Since all subtasks are closed, I'm closing this epic issue as well.
