### ISSUE TITLE
Rancher provisioned/managed RKE2/K3s data-dir support

### ISSUE THREAD

**Issue by jakefhyde** [rancher/elemental-operator#732]
There is currently an ongoing effort to support specifying the RKE2/K3s `data-dir` argument, which allows a user to change it from the default of `/var/lib/rancher/rke2` & `/var/lib/rancher/k3s` respectively, to a user provided directory. I've found the following instances of these directories hardcoded within the project:
- https://github.com/rancher/elemental-operator/blob/2bd467f301a45050000cbc3e7aa82454b79e8b29/cmd/support/main.go#L45
Additionally, the system agent will be receiving proper support for setting the `CATTLE_AGENT_VAR_DIR` via a field on the provisioning cluster object, which allows the users to configure the `/var/lib/rancher/agent` directory, and the following instances were identified to be hardcoded within the project:
- https://github.com/rancher/elemental-operator/blob/2bd467f301a45050000cbc3e7aa82454b79e8b29/cmd/support/main.go#L47
Please review the above information, and feel free to reach out to me regarding questions. The api changes can be found within this draft PR within rancher/rancher: https://github.com/rancher/rancher/pull/45326/files#diff-6f7b3ace8ec7df668da64642416a1171322908df345c8e339d314bac3ed08af6R57.

**Comment by anmazzotti** [comment]
Hello @jakefhyde, trying to get a fix for this. 

I can easily extract the agent plan dir from the agent config in `/etc/rancher/agent/config.yaml`, however I miss how to get the `data-dir`. 

This is a chicken-and-egg scenario, we can't use kubectl before locating where the binary is, hence I'm looking for some indication on the host where the data-dir has been defined. I do not think it will be propagated to `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` from the PR you linked.

I could try to parse `/etc/systemd/system/rke2-server.service` to lookup for this information, but I'm not entirely sure it will be present or easy to determine there too. 

Any input or recommendation you can give me? Thank you.

**Comment by jakefhyde** [comment]
`data-dir` is a RKE2/K3s flag, so it'll be top level.
