### ISSUE TITLE
Missing backports for hostname and reset in 1.5.3 operator

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#747]
I was testing the new operator we pushed in the marketplace (1.5.3 and os version 2.0.4) and I saw issues with hostname and reset.
I think we forgot to backport some fixes there.

![image](https://github.com/rancher/elemental-operator/assets/6025636/eaa98752-b2c4-4311-bb2d-7eb84728983c)
hostname should be node-001, node-002 and node-003

![image](https://github.com/rancher/elemental-operator/assets/6025636/6f6443a7-7402-46a0-b356-689f8c367eeb)
Machine inventory should not be set to `recovery` after a reset.

**Comment by fgiudici** [comment]
I would have expected to have all the backports in 1.5.3 and with the 2.0.4 images.
We have to double check.

**Comment by juadk** [comment]
False alarm, we cannot reproduce it manually so looks like something is wrong in the CI.
I will continu my manual tests and will check the CI later.
