### ISSUE TITLE
"elemental-operator register /run/initramfs/live" broken

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#78]
Setup:
- Rancher Manager running via Docker
- Client on KVM (virt-manager)
- self-signed certs

Full log (from `journalctl -t elemental`)
[elemental.log](https://github.com/rancher/elemental-operator/files/9166895/elemental.log)

**Comment by davidcassany** [comment]
are you sure you embedded the registration configuration file with the appropriate name? In order to execute `elemental-operator` the iso has to include in its root a file called `livecd-cloud-config.yaml` otherwise it won't be executed.

@Itxaka probably we could remove this file existance condition, after all `elemental-operator` will attempt to read all yaml files in the given folder, so even if there are other yaml files around it will attempt to read them.

**Comment by Itxaka** [comment]
Well it was mainly done in case the iso is built wrongly somehow, the operator will not launch automatically, so we dont get strange errors.

On @kkaempf logs it shows that it run the stage so the file is correctly set

```
Jul 22 10:16:59 localhost elemental[1605]: INFO[2022-07-22T10:16:59Z] Applying 'Elemental operator bootstrap' for stage 'network'. Total stages: 1
Jul 22 10:16:59 localhost elemental[1605]: INFO[2022-07-22T10:16:59Z] Processing stage step ''. ( commands: 1, files: 0, ... )
```

Problem is that becuase we have no streaming logs, the command is retrying and doesnt return, so it looks like its hanging. It could be a tpm error, a network error, a cacert error...and we will never know.

Maybe it wasnt such a good idea to remove the service files...at least we could see the output of the command :/

**Comment by kkaempf** [comment]
> @kkaempf are you sure you embedded the registration configuration file with the appropriate name? In order to execute `elemental-operator` the iso has to include in its root a file called `livecd-cloud-config.yaml` otherwise it won't be executed.

Yes, I checked this. The file is present and has the expected content.

**Comment by kkaempf** [comment]
> Maybe it wasnt such a good idea to remove the service files...at least we could see the output of the command :/

😞  🤔

**Comment by davidcassany** [comment]
> Problem is that becuase we have no streaming logs, the command is retrying and doesnt return, so it looks like its hanging. It could be a tpm error, a network error, a cacert error...and we will never know.

Well from the cloud-config execution it shouldn't be hard to log into a file or probably directly to journalctl with something like `elemental-operator --debug register /run/initramfs/live | systemd-cat`

**Comment by Itxaka** [comment]
@kkaempf 
 - image used for the node?
 - yaml used for the node (bar cert/registration token of course)?

**Comment by davidcassany** [comment]
related to this I just opened rancher/elemental#202

**Comment by davidcassany** [comment]
Damn with the removal of the unit service file we are hitting again #50 ... 😞 At least my env now seams to be consistently failing with this sort of race condition if a previously installed system was there.

**Comment by kkaempf** [comment]
It probably was all caused by the locked-up `swtpm` state. After unlocking it, everything works now.

Bottom line: We need more exhaustive logging

**Comment by Itxaka** [comment]
> It probably was all caused by the locked-up swtpm state. After unlocking it, everything works now.

HOW HOOOOOWWWW

![image](https://user-images.githubusercontent.com/1447686/180445805-0a45d53c-32e4-4a43-b31a-379025101ed6.png)

**Comment by kkaempf** [comment]
🤷🏻‍♂️ 😿
