### ISSUE TITLE
[SURE-8889] Provide a checksum for Elemental ISO builds

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#823]
### Request description:
Provide checksum on ISO build/downloads. When the seed image is created, a .sha256 checksum file be created as well so users can compare the downloaded ISO file

### Actual behavior:
Currently not a feature in Elemental. Download completed successfully but we had many issues with this ISO (which was most likely do bad network which we are not sure the download was complete) This would verify that the download is good before using it to spin up nodes/clusters. 

### Expected behavior:
Provide a checksum, if checksum doesn't match it should retry.

**Comment by anmazzotti** [comment]
Possibly https://github.com/rancher/elemental-ui/issues/222 is also part of this issue.

**Comment by mbologna** [comment]
The feature is done in backend, awaiting frontend (UI) implementation. Closing the backend issue.
