### ISSUE TITLE
ca-cert in config file breaks SSL for real certs

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#87]
If I have a real cert for my Rancher Manager (or something farther upstream is terminating the SSL), the inclusion of ca-cert breaks the registration command fails. While I can delete the key in the config that gets loaded in at install time, it's much harder to change the values that's loaded into `/oem/registration/config.yaml` for use in updating labels at run time. 

What would be nice is to have a way to tell the registration endpoint to not pass ca-cert through.

**Comment by fgiudici** [comment]
This is the same as #84 ... it should have been fixed by #85 , which landed in 0.4.0, but if it is not something more is missing

**Comment by kkaempf** [comment]
I'd consider this fixed by #85

**Comment by fgiudici** [comment]
Closing for now, please reopen if needed
