### ISSUE TITLE
add cattle-elemental-system in the list of system namespaces in Rancher

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-operator#9]
We have to make sure that `cattle-elemental-system` is propagated in the system namespaces in Rancher.

https://github.com/rancher/elemental-operator/pull/3#issuecomment-1173929099

cc @pgonin to figure out how we can track progress on this

**Comment by pgonin** [comment]
What version should we request to get included in Rancher system namespaces ?  2.7 ?

**Comment by pgonin** [comment]
https://github.com/rancher/rancher/pull/39064

**Comment by mjura** [comment]
Besides adding `cattle-elemental-system` to backup, we have to also add all CRD's definition and objects created by `elemental-operator` to `rancher-backup` operator 

This was proposed https://github.com/rancher/backup-restore-operator/pull/277

**Comment by kkaempf** [comment]
@pgonin - this probably needs to be escalated via the management foodchain :-/

**Comment by kkaempf** [comment]
M.E.R.G.E.D. 🤯
