### ISSUE TITLE
Set hostname in cloud-config?

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#90]
Previously, `hostname` property was allowed/set in `cloud-config` section to set the server hostname upon booting. Now this property is not allowed anymore, and `machineName` can be used for this if it is set only (this means that the default value of `machineName` will not be used to set the hostname if nothing is provided).
**EDIT:** on my last test the hostname is always `localhost`, so it seems that `machineName` is not used anymore to set the hostname? In fact after a reboot I have something like `rancher-XXXXX` as a hostname...

I tried to set `machineName` to something else: `machineName: node-{{ trunc 4 .MachineID }}` but in that case the automated installation is not executed, and `MachineInventories` is not created in Rancher Dashboard either. No error in the operator logs, I can see that Rancher Dashboard is contacted but nothin more.

We need a way to be able to set the hostname as setting `machineName` to something else doesn't seems to work (sounds like the `clusterName` property in Rancher, maybe `machineName` should be always auto-generated in readonly?). Maybe DHCP can bue used to set a hostname, but lot of customers may need to be able to force a hostname with a fixed IP.

**Comment by fgiudici** [comment]
> I tried to set `machineName` to something else: `machineName: node-{{ trunc 4 .MachineID }}` but in that case the automated installation is not executed, and `MachineInventories` is not created in Rancher Dashboard either. No error in the operator logs, I can see that Rancher Dashboard is contacted but nothin more.

Changing the `machineName` shouldn't hang the installation.. the bare minimum here and the first step is to improve logging (and try to figure out what happened).

How the hostname "should be" set should also be reviewed: after reboot, Rancher Manager hostname takes over in any case (rancher-XXXXX). How the hostname is expected to be managed is not clear as today. Making this clear is part of the things to address in this issue.

**Comment by ldevulder** [comment]
After adding an installed node to a cluster I finally have the hostname set to the value of `machineName`, so it's still clearly used to set the hostname.

**Comment by kkaempf** [comment]
see also #97

**Comment by ldevulder** [comment]
> see also #97

Manually tested and it works! But is there any plan to be able to set a custom hostname? Something like the `hostname` property in `cloud-config` like we had before?

**Comment by Itxaka** [comment]
latest patch from @mjura fixes this I think, now the hostname is set properly on bootstrap and it also survive reboots: https://github.com/rancher/elemental-operator/pull/106

**Comment by ldevulder** [comment]
> latest patch from @mjura fixes this I think

But how the hostname can be configured to something different than `rancher-XXXX`? The latest patches seem to "only" fix the persisent across reboot (which is good of course ;-)).

**Comment by Itxaka** [comment]
Ah this is only possible via MachineName for now, not manually. MachineName takes precedence over everything else, even if you set a hostname in cloud-init. You could do it and it would be used on each reboot as yip would set it but why would you do that? You only want one source for the hostname and this are cattle, so it should be autogenerated via the bootstrap methods.

@mjura patch fixes the hostname name change for rancher-XXXX to only set what machineinventory wants. 

Changing the hostname against what the k8s inventory sets could bring also a lot of issues.

**Comment by kkaempf** [comment]
I consider this issue done.
If new evidence appears, please open a new issue.

**Comment by Itxaka** [comment]
maybe an improvement would be to set the hostname to elemental-XXXX instead of rancher so we know we are setting the initial hostname ourselves and dont blame rancher :rofl:

**Comment by ldevulder** [comment]
I don't understand something: we can't set the hostname to something else, for example `my-own-name-XXXX`? If so this could be an issue for some users. Where I worked before only "valid" hostname was allowed ("valid" means codified hostname).
